'use strict';
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {URL}=require('node:url');
const {RigDatabase,SCHEMA_VERSION,DB_SCHEMA_VERSION}=require('./database');
const {loadConfig,ROOT}=require('./config');
const {AuthBoundary}=require('./auth');
const {applySecurityHeaders,assertSameOrigin,createRateLimiter}=require('./security');
const {TrustedAuthGateway}=require('./auth-gateway');
const {createLogger,createMetrics,requestFingerprint}=require('./observability');
const {AssetVault,sha256}=require('./asset-vault');
const {AssetDeliverySigner}=require('./asset-delivery');

const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};
function readJson(req,limitBytes){return new Promise((resolve,reject)=>{const declared=Number(req.headers['content-length']||0);if(declared&&declared>limitBytes){const e=Object.assign(new Error('Request too large'),{status:413,code:'payload_too_large'});reject(e);req.resume();return}let size=0,chunks=[];req.on('data',c=>{size+=c.length;if(size>limitBytes){reject(Object.assign(new Error('Request too large'),{status:413,code:'payload_too_large'}));req.destroy();return}chunks.push(c)});req.on('end',()=>{if(!chunks.length)return resolve({});const body=Buffer.concat(chunks).toString('utf8');try{resolve(JSON.parse(body))}catch{reject(Object.assign(new Error('Invalid JSON body'),{status:400,code:'invalid_json'}))}});req.on('error',reject)})}

function readBuffer(req,limitBytes){return new Promise((resolve,reject)=>{const declared=Number(req.headers['content-length']||0);if(declared&&declared>limitBytes){reject(Object.assign(new Error('Asset binary too large'),{status:413,code:'payload_too_large'}));req.resume();return}let size=0,chunks=[];req.on('data',c=>{size+=c.length;if(size>limitBytes){reject(Object.assign(new Error('Asset binary too large'),{status:413,code:'payload_too_large'}));req.destroy();return}chunks.push(c)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}

function send(res,status,data,headers={}){const isBuffer=Buffer.isBuffer(data),body=isBuffer?data:data==null?'':typeof data==='string'?data:JSON.stringify(data,null,2);const base={'cache-control':'no-store',...(isBuffer?{}:{'content-type':'application/json; charset=utf-8'})};res.writeHead(status,{...base,...headers});res.end(body)}
function errorEnvelope(err,requestId){const status=err.status||(err.code==='version_conflict'?409:err.code==='validation_error'||err.code==='quote_gate_blocked'?422:500);return {status,payload:{error:err.code||'server_error',code:err.code||'server_error',message:err.message||'Server error',fieldErrors:err.fieldErrors||[],currentVersion:err.currentVersion,retryAfter:err.retryAfter,requestId}}}
function requireRole(actor,roles){if(!actor||!roles.includes(actor.role)){const e=new Error(`Role ${actor?.role||'anonymous'} is not permitted for this operation`);e.status=403;e.code='forbidden';throw e}}
function safeStaticPath(urlPath){const rel=decodeURIComponent(urlPath==='/'?'/index.html':urlPath).replace(/^\/+/,''),full=path.resolve(ROOT,rel);if(!full.startsWith(ROOT+path.sep)&&full!==ROOT)return null;return full}
function sessionPayload(ctx,config){return {schemaVersion:SCHEMA_VERSION,authenticated:ctx.source==='session'||ctx.source==='session-new',source:ctx.source,actor:ctx.actor,expiresAt:ctx.session?.expiresAt||null,capabilities:{devLogin:config.allowDevLogin,prototypeHeaders:config.allowPrototypeHeaders},production:config.production}}

function createApp({dbFile,seed=true,config:configOverrides={}}={}){
  const config=loadConfig({...configOverrides,...(dbFile?{dbFile}:{})});
  const db=new RigDatabase(config.dbFile);
  const assetVault=new AssetVault(config);
  const assetDelivery=new AssetDeliverySigner(config.assetDeliverySecret,{ttlSeconds:config.assetSignedUrlTtlSeconds,publicOrigin:config.publicOrigin});
  const gateway=new TrustedAuthGateway(config),auth=new AuthBoundary(db,config,{gateway}),rateLimit=createRateLimiter(config),logger=createLogger(config),metrics=createMetrics();
  if(seed&&!db.getCatalogue('nissan-y62-warrior-2025')){try{const bundle=JSON.parse(fs.readFileSync(path.join(ROOT,'seed','bootstrap.seed.json'),'utf8'));db.importSeed(bundle,{actor:{actorId:'bootstrap',displayName:'Bootstrap Seed',role:'admin',scopes:['*'],prototype:false}})}catch(e){console.error('Bootstrap seed failed:',e.message)}}
  const server=http.createServer(async(req,res)=>{
    const requestId=`REQ-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`,started=process.hrtime.bigint();
    let metricStatus=500;
    try{
      applySecurityHeaders(req,res,config,requestId);
      const u=new URL(req.url,'http://localhost'),pathname=u.pathname;
      const rl=rateLimit(req,pathname);if(rl){res.setHeader('x-ratelimit-remaining',String(rl.remaining));res.setHeader('x-ratelimit-reset',String(Math.ceil(rl.resetAt/1000)))}
      if(pathname.startsWith('/api/'))assertSameOrigin(req,config);

      if(pathname==='/api/v1/health'&&req.method==='GET'){const ds=db.getDatabaseStatus();metricStatus=200;return send(res,200,{ok:true,schemaVersion:SCHEMA_VERSION,dbSchemaVersion:ds.dbSchemaVersion,migrationVersion:ds.migrationVersion,service:'pro4x4-rig-builder',authMode:gateway.enabled()?'trusted-gateway+session-cookie':'server-session-cookie',environment:config.env,database:path.basename(config.dbFile),identityGateway:{enabled:gateway.enabled(),emailDomain:config.authGatewayEmailDomain||null},assetStorage:{...assetVault.status(),signedDeliveryTtlSeconds:config.assetSignedUrlTtlSeconds,deliverySecretEphemeral:config.assetDeliverySecretEphemeral},metrics:config.metricsEnabled})}
      if(pathname==='/api/v1/ready'&&req.method==='GET'){const ds=db.getDatabaseStatus(),ready=ds.migrationVersion===DB_SCHEMA_VERSION;metricStatus=ready?200:503;return send(res,metricStatus,{ready,dbSchemaVersion:ds.dbSchemaVersion,migrationVersion:ds.migrationVersion,expectedMigrationVersion:DB_SCHEMA_VERSION})}
      if(pathname==='/metrics'&&req.method==='GET'){if(!config.metricsEnabled)return send(res,404,'Not found',{'content-type':'text/plain; charset=utf-8'});if(config.metricsToken&&req.headers.authorization!==`Bearer ${config.metricsToken}`)return send(res,401,'Unauthorized',{'content-type':'text/plain; charset=utf-8'});metricStatus=200;return send(res,200,metrics.render(),{'content-type':'text/plain; version=0.0.4; charset=utf-8','cache-control':'no-store'})}
      if(pathname==='/api/v1/auth/dev-login'&&req.method==='POST'){const body=await readJson(req,config.requestBodyLimitBytes),issued=auth.devLogin(req,res,body);return send(res,201,{schemaVersion:SCHEMA_VERSION,authenticated:true,source:'session',actor:issued.actor,expiresAt:issued.expiresAt,production:config.production})}
      if(pathname==='/api/v1/auth/session'&&req.method==='GET'){const ctx=auth.resolve(req,res);return send(res,200,sessionPayload(ctx,config))}
      if(pathname==='/api/v1/auth/logout'&&req.method==='POST'){const ctx=auth.resolve(req,res);auth.logout(req,res,ctx.actor);return send(res,200,{schemaVersion:SCHEMA_VERSION,loggedOut:true})}

      let actor=null,ctx=null;
      if(pathname.startsWith('/api/')){ctx=auth.resolve(req,res);actor=ctx.actor}

      if(pathname==='/api/v1/builds'&&req.method==='POST'){const body=await readJson(req,config.requestBodyLimitBytes);return send(res,201,db.upsertQuote(body,{actor,action:'quote.submitted'}))}
      if(pathname==='/api/v1/render/resolve'&&req.method==='POST'){const body=await readJson(req,config.requestBodyLimitBytes);return send(res,200,db.resolveProductionRenderStack(body))}
      if(pathname==='/api/v1/render/telemetry'&&req.method==='POST'){const body=await readJson(req,config.requestBodyLimitBytes);const event=db.recordRenderTelemetry(body,{actor});metrics.inc('pro4x4_render_telemetry_total',{event:event.eventType,view:event.viewId});return send(res,202,{accepted:true,id:event.id,at:event.at})}
      if(pathname==='/api/v1/staff/quotes'&&req.method==='GET'){requireRole(actor,['sales','fitment','admin']);return send(res,200,db.listQuotes())}
      let m=pathname.match(/^\/api\/v1\/staff\/quotes\/([^/]+)$/);if(m&&req.method==='GET'){requireRole(actor,['sales','fitment','admin']);const q=db.getQuote(decodeURIComponent(m[1]));if(!q)return send(res,404,{error:'not_found',code:'not_found',message:'Quote not found',requestId});return send(res,200,q)}
      if(m&&req.method==='PATCH'){requireRole(actor,['sales','fitment','admin']);const body=await readJson(req,config.requestBodyLimitBytes),q=db.updateQuote(decodeURIComponent(m[1]),body,{actor});if(!q)return send(res,404,{error:'not_found',code:'not_found',message:'Quote not found',requestId});return send(res,200,q)}
      m=pathname.match(/^\/api\/v1\/staff\/quotes\/([^/]+)\/finalise$/);if(m&&req.method==='POST'){requireRole(actor,['sales','admin']);const q=db.finaliseQuote(decodeURIComponent(m[1]),{actor});if(!q)return send(res,404,{error:'not_found',code:'not_found',message:'Quote not found',requestId});return send(res,200,q)}
      if(pathname==='/api/v1/staff/settings/quote'&&req.method==='GET'){requireRole(actor,['sales','fitment','admin']);return send(res,200,db.getSettings())}
      if(pathname==='/api/v1/staff/settings/quote'&&req.method==='PATCH'){requireRole(actor,['sales','admin']);return send(res,200,db.setSettings(await readJson(req,config.requestBodyLimitBytes),{actor}))}
      m=pathname.match(/^\/api\/v1\/catalogue\/([^/]+)$/);if(m&&req.method==='GET'){const c=db.getCatalogue(decodeURIComponent(m[1]));if(!c)return send(res,404,{error:'not_found',code:'not_found',message:'Catalogue not found',requestId});return send(res,200,c)}
      m=pathname.match(/^\/api\/v1\/staff\/catalogue\/([^/]+)\/revisions$/);if(m&&req.method==='POST'){requireRole(actor,['fitment','admin']);return send(res,201,db.publishCatalogue(decodeURIComponent(m[1]),await readJson(req,config.requestBodyLimitBytes),{actor}))}
      m=pathname.match(/^\/api\/v1\/staff\/catalogue\/([^/]+)\/draft$/);if(m&&req.method==='GET'){requireRole(actor,['fitment','admin']);return send(res,200,db.getCatalogueDraft(decodeURIComponent(m[1])))}
      if(m&&req.method==='PUT'){requireRole(actor,['fitment','admin']);return send(res,200,db.saveCatalogueDraft(decodeURIComponent(m[1]),await readJson(req,config.requestBodyLimitBytes),{actor}))}
      if(m&&req.method==='DELETE'){requireRole(actor,['fitment','admin']);db.discardCatalogueDraft(decodeURIComponent(m[1]),{actor});return send(res,204,null)}
      if(pathname==='/api/v1/staff/render-assets'&&req.method==='GET'){requireRole(actor,['fitment','admin']);return send(res,200,db.listRenderAssets({vehicleId:u.searchParams.get('vehicleId'),viewId:u.searchParams.get('viewId'),status:u.searchParams.get('status')}))}
      if(pathname==='/api/v1/staff/visual-governance/sync'&&req.method==='POST'){requireRole(actor,['fitment','admin']);const body=await readJson(req,config.requestBodyLimitBytes);return send(res,200,db.syncVisualGovernanceRegistry({vehicleId:body.vehicleId||'nissan-y62-warrior-2025'},{actor}))}
      if(pathname==='/api/v1/staff/render-readiness'&&req.method==='GET'){requireRole(actor,['sales','fitment','admin']);return send(res,200,db.renderReadiness({vehicleId:u.searchParams.get('vehicleId')||undefined,telemetryHours:u.searchParams.get('telemetryHours')||undefined}))}
      if(pathname==='/api/v1/staff/render-readiness/slots/sync'&&req.method==='POST'){requireRole(actor,['fitment','admin']);const body=await readJson(req,config.requestBodyLimitBytes);return send(res,200,db.syncRenderReadinessSlots({vehicleId:body.vehicleId||undefined},{actor}))}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/reference-source$/);if(m&&req.method==='GET'){requireRole(actor,['fitment','admin']);const asset=db.getRenderAsset(decodeURIComponent(m[1]));if(!asset||asset.assetClass!=='reference'||!asset.source)return send(res,404,{error:'not_found',code:'not_found',message:'Reference source not found',requestId});const refsRoot=path.resolve(ROOT,'references'),file=path.resolve(ROOT,asset.source);if(!(file===refsRoot||file.startsWith(refsRoot+path.sep))||!fs.existsSync(file)||!fs.statSync(file).isFile())return send(res,404,{error:'not_found',code:'not_found',message:'Reference source file not found',requestId});const buf=fs.readFileSync(file),actual=sha256(buf),expected=asset.file?.checksumSha256||null;if(expected&&actual!==expected)return send(res,409,{error:'reference_checksum_mismatch',code:'reference_checksum_mismatch',message:'Reference source checksum no longer matches its provenance record',requestId});return send(res,200,buf,{'content-type':mime[path.extname(file).toLowerCase()]||'application/octet-stream','content-length':String(buf.length),'etag':`"sha256-${actual}"`,'cache-control':'private, no-store'})}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/versions$/);if(m&&req.method==='GET'){requireRole(actor,['fitment','admin']);return send(res,200,db.listAssetVersions(decodeURIComponent(m[1])))}
      if(m&&req.method==='POST'){requireRole(actor,['fitment','admin']);const assetId=decodeURIComponent(m[1]),buf=await readBuffer(req,config.assetBodyLimitBytes);if(!buf.length)throw Object.assign(new Error('Asset binary is empty'),{status:422,code:'validation_error'});const object=await assetVault.put(assetId,buf),version=db.stageAssetVersion(assetId,object,{actor});return send(res,201,{version,object:{objectKey:object.objectKey,checksumSha256:object.checksumSha256,mimeType:object.mimeType,width:object.width,height:object.height,hasAlpha:object.hasAlpha,transparencyVerified:object.transparencyVerified,sizeBytes:object.sizeBytes}})}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/versions\/([^/]+)$/);if(m&&req.method==='PUT'){requireRole(actor,['fitment','admin']);const assetId=decodeURIComponent(m[1]),versionId=decodeURIComponent(m[2]),body=await readJson(req,config.requestBodyLimitBytes);return send(res,200,db.updateAssetVersion(assetId,versionId,body,{actor}))}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/versions\/([^/]+)\/promote$/);if(m&&req.method==='POST'){requireRole(actor,['fitment','admin']);return send(res,200,db.promoteAssetVersion(decodeURIComponent(m[1]),decodeURIComponent(m[2]),{actor}))}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/versions\/([^/]+)\/reject$/);if(m&&req.method==='POST'){requireRole(actor,['fitment','admin']);const body=await readJson(req,config.requestBodyLimitBytes);return send(res,200,db.rejectAssetVersion(decodeURIComponent(m[1]),decodeURIComponent(m[2]),body.note,{actor}))}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/versions\/([^/]+)\/delivery$/);if(m&&req.method==='GET'){requireRole(actor,['fitment','admin']);const assetId=decodeURIComponent(m[1]),versionId=decodeURIComponent(m[2]),version=db.getAssetVersion(assetId,versionId);if(!version)return send(res,404,{error:'not_found',code:'not_found',message:'Asset version not found',requestId});const expiresAt=new Date(Date.now()+config.assetSignedUrlTtlSeconds*1000).toISOString(),direct=assetVault.presignGet(version.objectKey,config.assetSignedUrlTtlSeconds);let url,mode;if(direct){url=direct;mode='s3-presigned'}else{const token=assetDelivery.sign({assetId,versionId,objectKey:version.objectKey,checksumSha256:version.checksumSha256},{ttlSeconds:config.assetSignedUrlTtlSeconds});url=assetDelivery.url(token);mode='signed-local'}db.audit('render.asset.version.delivery.issued','render-asset',assetId,{versionId,state:version.state,mode,expiresAt},actor);return send(res,200,{schemaVersion:SCHEMA_VERSION,assetId,versionId,state:version.state,checksumSha256:version.checksumSha256,delivery:{mode,url,expiresAt,ttlSeconds:config.assetSignedUrlTtlSeconds}})}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)$/);if(m&&req.method==='PUT'){requireRole(actor,['fitment','admin']);const body=await readJson(req,config.requestBodyLimitBytes);if(decodeURIComponent(m[1])!==body.assetId)throw Object.assign(new Error('Asset ID mismatch'),{code:'validation_error'});return send(res,200,db.upsertRenderAsset(body,{actor}))}
      m=pathname.match(/^\/api\/v1\/staff\/render-assets\/([^/]+)\/binary$/);if(m&&req.method==='PUT'){requireRole(actor,['fitment','admin']);const assetId=decodeURIComponent(m[1]),buf=await readBuffer(req,config.assetBodyLimitBytes);if(!buf.length)throw Object.assign(new Error('Asset binary is empty'),{status:422,code:'validation_error'});const object=await assetVault.put(assetId,buf),out=db.attachAssetObject(assetId,object,{actor});return send(res,201,{asset:out,object:db.getAssetObject(assetId)})}
      if(m&&req.method==='GET'){requireRole(actor,['fitment','admin']);const assetId=decodeURIComponent(m[1]),obj=db.getAssetObject(assetId);if(!obj)return send(res,404,{error:'not_found',code:'not_found',message:'Asset binary not found',requestId});const buf=await assetVault.read(obj.objectKey);if(!buf)return send(res,410,{error:'asset_binary_missing',code:'asset_binary_missing',message:'Asset vault metadata exists but binary is unavailable',requestId});return send(res,200,buf,{'content-type':obj.mimeType,'content-length':String(buf.length),'etag':`"sha256-${obj.checksumSha256}"`,'cache-control':'private, max-age=3600'})}
      if(pathname==='/api/v1/staff/audit'&&req.method==='GET'){requireRole(actor,['sales','fitment','admin']);return send(res,200,db.listAudit({entityType:u.searchParams.get('entityType'),entityId:u.searchParams.get('entityId'),action:u.searchParams.get('action'),limit:u.searchParams.get('limit')||200}))}
      if(pathname==='/api/v1/staff/render-telemetry'&&req.method==='GET'){requireRole(actor,['sales','fitment','admin']);return send(res,200,db.listRenderTelemetry({vehicleId:u.searchParams.get('vehicleId'),viewId:u.searchParams.get('viewId'),eventType:u.searchParams.get('eventType'),limit:u.searchParams.get('limit')||100}))}
      if(pathname==='/api/v1/projects'&&req.method==='GET')return send(res,200,db.listProjects({actor}));
      m=pathname.match(/^\/api\/v1\/projects\/([^/]+)$/);if(m&&req.method==='GET'){const p=db.getProject(decodeURIComponent(m[1]),{actor});if(!p)return send(res,404,{error:'not_found',code:'not_found',message:'Project not found',requestId});return send(res,200,p)}
      m=pathname.match(/^\/api\/v1\/projects\/([^/]+)\/revisions$/);if(m&&req.method==='POST'){const body=await readJson(req,config.requestBodyLimitBytes);return send(res,201,db.saveProjectRevision(decodeURIComponent(m[1]),body.snapshot,{expectedVersion:body.expectedVersion,source:body.source,actor}))}
      m=pathname.match(/^\/api\/v1\/projects\/([^/]+)\/current-revision$/);if(m&&req.method==='PUT'){const body=await readJson(req,config.requestBodyLimitBytes),out=db.restoreProjectRevision(decodeURIComponent(m[1]),body.revisionId,{expectedVersion:body.expectedVersion,actor});if(!out)return send(res,404,{error:'not_found',code:'not_found',message:'Project not found',requestId});return send(res,200,out)}
      m=pathname.match(/^\/api\/v1\/projects\/([^/]+)\/shares$/);if(m&&req.method==='POST'){const out=db.createShare(decodeURIComponent(m[1]),await readJson(req,config.requestBodyLimitBytes),{actor});if(!out)return send(res,404,{error:'not_found',code:'not_found',message:'Project not found',requestId});return send(res,201,out)}
      m=pathname.match(/^\/api\/v1\/projects\/([^/]+)\/shares\/([a-f0-9]{64})$/i);if(m&&req.method==='DELETE'){const ok=db.revokeShareHash(decodeURIComponent(m[1]),m[2],{actor});if(!ok)return send(res,404,{error:'not_found',code:'not_found',message:'Share not found',requestId});return send(res,204,null)}
      m=pathname.match(/^\/api\/v1\/shares\/([^/]+)$/);if(m&&req.method==='GET'){const out=db.resolveShare(decodeURIComponent(m[1]));if(!out)return send(res,404,{error:'not_found',code:'not_found',message:'Share not found, expired or revoked',requestId});return send(res,200,out)}
      if(m&&req.method==='DELETE'){const ok=db.revokeShare(decodeURIComponent(m[1]),{actor});if(!ok)return send(res,404,{error:'not_found',code:'not_found',message:'Share not found',requestId});return send(res,204,null)}
      if(pathname==='/api/v1/admin/import/seed'&&req.method==='POST'){requireRole(actor,['admin']);return send(res,200,db.importSeed(await readJson(req,config.requestBodyLimitBytes),{actor}))}
      if(pathname==='/api/v1/admin/asset-vault/status'&&req.method==='GET'){requireRole(actor,['admin']);const refs=db.listVaultReferences(),files=await assetVault.inventory(),refMap=new Map(refs.map(x=>[x.objectKey,x])),fileMap=new Map(files.map(x=>[x.objectKey,x]));const missing=refs.filter(x=>!fileMap.has(x.objectKey));const orphaned=files.filter(x=>!refMap.has(x.objectKey));const corrupt=[];for(const ref of refs){if(fileMap.has(ref.objectKey)){const v=await assetVault.verify(ref.objectKey,ref.checksumSha256);if(!v.checksumMatches)corrupt.push({...ref,actualChecksumSha256:v.checksumSha256})}}const status={schemaVersion:SCHEMA_VERSION,checkedAt:new Date().toISOString(),storage:assetVault.status(),referencedObjects:refs.length,vaultFiles:files.length,missing,orphaned,corrupt,healthy:missing.length===0&&corrupt.length===0,totalBytes:files.reduce((n,x)=>n+x.sizeBytes,0)};return send(res,200,status)}
      if(pathname==='/api/v1/admin/asset-vault/gc'&&req.method==='POST'){requireRole(actor,['admin']);const body=await readJson(req,config.requestBodyLimitBytes),refs=new Set(db.listVaultReferences().map(x=>x.objectKey)),orphans=(await assetVault.inventory()).filter(x=>!refs.has(x.objectKey));let removed=[];if(body?.execute===true){for(const o of orphans)if(await assetVault.remove(o.objectKey))removed.push(o.objectKey);db.audit('asset.vault.gc','system','asset-vault',{storageDriver:assetVault.mode,removedCount:removed.length,removed},actor)}return send(res,200,{schemaVersion:SCHEMA_VERSION,storage:assetVault.status(),dryRun:body?.execute!==true,orphanCount:orphans.length,orphans,removed})}
      if(pathname==='/api/v1/admin/backup'&&req.method==='GET'){requireRole(actor,['admin']);const b=db.backup(),refs=db.listVaultReferences();b.assetStorage=assetVault.status();b.vaultManifest=await Promise.all(refs.map(async r=>({...r,verification:await assetVault.verify(r.objectKey,r.checksumSha256)})));b.vaultManifestHealthy=b.vaultManifest.every(x=>x.verification.exists&&x.verification.checksumMatches);return send(res,200,b)}
      if(pathname==='/api/v1/admin/backup/restore'&&req.method==='POST'){requireRole(actor,['admin']);return send(res,200,db.restoreBackup(await readJson(req,config.backupBodyLimitBytes),{actor}))}
      m=pathname.match(/^\/api\/v1\/render-assets\/version-delivery\/([^/]+)$/);if(m&&req.method==='GET'){const claims=assetDelivery.verify(decodeURIComponent(m[1])),version=db.getAssetVersion(claims.assetId,claims.versionId);if(!version||version.objectKey!==claims.objectKey||version.checksumSha256!==claims.checksumSha256)return send(res,404,{error:'not_found',code:'not_found',message:'Historical asset version not found',requestId});const buf=await assetVault.read(version.objectKey);if(!buf)return send(res,410,{error:'asset_binary_missing',code:'asset_binary_missing',message:'Historical asset binary is unavailable',requestId});if(sha256(buf)!==version.checksumSha256)return send(res,409,{error:'asset_binary_corrupt',code:'asset_binary_corrupt',message:'Historical asset checksum verification failed',requestId});db.audit('render.asset.version.delivery.accessed','render-asset',version.assetId,{versionId:version.versionId,state:version.state,storageDriver:assetVault.mode},{actorId:'signed-asset-delivery',displayName:'Signed Asset Delivery',role:'system'});return send(res,200,buf,{'content-type':version.mimeType,'content-length':String(buf.length),'etag':`"sha256-${version.checksumSha256}"`,'cache-control':'private, no-store','content-disposition':`inline; filename="${version.versionId}.${version.mimeType==='image/webp'?'webp':'png'}"`})}
      m=pathname.match(/^\/api\/v1\/render-assets\/([^/]+)\/binary$/);if(m&&req.method==='GET'){const assetId=decodeURIComponent(m[1]),asset=db.getRenderAsset(assetId);if(!asset||asset.status!=='production-ready')return send(res,404,{error:'not_found',code:'not_found',message:'Production asset not found',requestId});const obj=db.getAssetObject(assetId);if(!obj)return send(res,404,{error:'not_found',code:'not_found',message:'Production asset binary not found',requestId});const requestedSha=u.searchParams.get('sha');if(requestedSha&&requestedSha!==obj.checksumSha256)return send(res,409,{error:'asset_version_changed',code:'asset_version_changed',message:'Requested production asset checksum is no longer active',requestId});const cdn=assetVault.publicUrl(obj.objectKey);if(cdn){res.writeHead(302,{location:cdn,'cache-control':requestedSha?'public, max-age=31536000, immutable':'public, max-age=300','etag':`"sha256-${obj.checksumSha256}"`});return res.end()}const buf=await assetVault.read(obj.objectKey);if(!buf)return send(res,404,{error:'not_found',code:'not_found',message:'Production asset binary not found',requestId});return send(res,200,buf,{'content-type':obj.mimeType,'content-length':String(buf.length),'etag':`"sha256-${obj.checksumSha256}"`,'cache-control':requestedSha?'public, max-age=31536000, immutable':'public, max-age=300'})}
      if(pathname.startsWith('/api/'))return send(res,404,{error:'not_found',code:'not_found',message:'API route not found',requestId});
      if(pathname.startsWith('/references/'))return send(res,404,'Not found',{'content-type':'text/plain; charset=utf-8'});

      const file=safeStaticPath(pathname);if(!file||!fs.existsSync(file)||!fs.statSync(file).isFile())return send(res,404,'Not found',{'content-type':'text/plain; charset=utf-8'});return send(res,200,fs.readFileSync(file),{'content-type':mime[path.extname(file).toLowerCase()]||'application/octet-stream','cache-control':'no-cache'});
    }catch(err){const out=errorEnvelope(err,requestId),headers={};metricStatus=out.status;if(out.status===429&&err.retryAfter)headers['retry-after']=String(err.retryAfter);logger.error('request.error',{requestId,method:req.method,path:req.url,status:out.status,code:out.payload.code,fingerprint:requestFingerprint(req)});send(res,out.status,out.payload,headers)}finally{const seconds=Number(process.hrtime.bigint()-started)/1e9,status=Number(res.statusCode||metricStatus||500);metrics.inc('pro4x4_http_requests_total',{method:req.method,status:String(status)});metrics.observe('pro4x4_http_request_duration_seconds',{method:req.method},seconds);logger.info('request.complete',{requestId,method:req.method,path:req.url,status,durationMs:Math.round(seconds*1000),fingerprint:requestFingerprint(req)})}
  });
  return {server,db,config,auth,gateway,logger,metrics,assetVault,assetDelivery};
}

if(require.main===module){
  const config=loadConfig();const {server,db}=createApp({config});server.listen(config.port,config.host,()=>console.log(`PRO4X4 Rig Builder Alpha 22: http://${config.host}:${config.port} · ${config.env} · hosted-ready auth`));const stop=()=>server.close(()=>{db.close();process.exit(0)});process.on('SIGINT',stop);process.on('SIGTERM',stop);
}
module.exports={createApp};
