const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
if(window.PRO4X4_AUTH?.current?.().role!=='admin')window.PRO4X4_AUTH.setLocalRole('admin','PRO4X4 Admin');
const backend=window.PRO4X4_BACKEND.active();let selectedBackup=null;$('#runtimeMode').textContent=backend.mode.toUpperCase();
async function health(){const box=$('#healthState');box.className='validation-box';box.textContent='Checking runtime…';try{const h=await backend.health();box.className='validation-box ok';box.innerHTML=`<b>Runtime healthy</b><div>Service: ${esc(h.service||backend.mode)}</div><div>Contract: ${esc(h.schemaVersion||'0.12.0')}</div><div>DB schema: ${esc(h.dbSchemaVersion??'local')}</div><div>Auth: ${esc(h.authMode||'browser-local')}</div>${h.environment?`<div>Environment: ${esc(h.environment)}</div>`:''}${h.database?`<div>Database: ${esc(h.database)}</div>`:''}${h.assetStorage?`<div>Asset storage: ${esc(h.assetStorage.driver||'local')} · CDN ${h.assetStorage.cdnEnabled?'enabled':'off'}</div>`:''}`}catch(e){box.className='validation-box has-errors';box.innerHTML=`<b>Runtime unavailable</b><div>${esc(e.message)}</div>`}}
function download(name,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
async function exportBackup(){const msg=$('#backupMessage');msg.textContent='Creating portable backup…';try{const b=await backend.exportBackup();download(`PRO4X4-RigBuilder-Backup-${new Date().toISOString().slice(0,10)}.json`,b);msg.textContent=`Backup exported from ${backend.mode}.`;}catch(e){msg.textContent=`Backup failed: ${e.message}`}}
$('#backupFile').onchange=async e=>{const f=e.target.files?.[0];selectedBackup=null;$('#restoreBackup').disabled=true;if(!f)return;try{selectedBackup=JSON.parse(await f.text());$('#restoreBackup').disabled=false;$('#backupMessage').textContent=`Selected ${f.name} · schema ${selectedBackup.schemaVersion||'unknown'}.`;}catch(err){$('#backupMessage').textContent=`Could not read backup: ${err.message}`}}
$('#restoreBackup').onclick=async()=>{if(!selectedBackup)return;const msg=$('#backupMessage');msg.textContent='Restoring selected backup…';try{const r=await backend.restoreBackup(selectedBackup);msg.textContent=`Restore complete · ${r.quoteCount??r.entryCount??0} quote/data records reported. Refresh staff screens before continuing.`;await health()}catch(e){msg.textContent=`Restore failed: ${e.message}`}}
$('#exportBackup').onclick=exportBackup;$('#refreshHealth').onclick=health;health();

async function vaultHealth(){const box=$('#vaultState');if(!box)return;box.textContent='Verifying governed objects…';try{const v=await backend.getAssetVaultStatus();box.className='validation-box '+(v.healthy?'ok':'has-errors');box.innerHTML=`<b>${v.healthy?'Vault integrity healthy':'Vault requires attention'}</b><div>Storage: ${esc(v.storage?.driver||'local')} · CDN ${v.storage?.cdnEnabled?'enabled':'off'}</div><div>Referenced: ${v.referencedObjects||0} · files: ${v.vaultFiles||0} · ${(v.totalBytes||0).toLocaleString()} bytes</div><div>Missing: ${(v.missing||[]).length} · corrupt: ${(v.corrupt||[]).length} · orphaned: ${(v.orphaned||[]).length}</div>`}catch(e){box.className='validation-box has-errors';box.textContent=`Vault check failed: ${e.message}`}}
async function gcVault(execute){const msg=$('#vaultMessage');msg.textContent=execute?'Removing unreferenced vault objects…':'Scanning for unreferenced vault objects…';try{const r=await backend.gcAssetVault(execute);msg.textContent=execute?`Removed ${r.removed.length} orphan object(s).`:`Dry run: ${r.orphanCount} orphan object(s) would be removed.`;await vaultHealth()}catch(e){msg.textContent=`Vault GC failed: ${e.message}`}}
$('#refreshVault')?.addEventListener('click',vaultHealth);$('#dryRunGc')?.addEventListener('click',()=>gcVault(false));$('#executeGc')?.addEventListener('click',()=>gcVault(true));vaultHealth();
