const backend=window.PRO4X4_BACKEND.active(),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let activeId=new URLSearchParams(location.search).get('project'),projects=[];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(n)||0);
const fmt=d=>d?new Date(d).toLocaleString('en-AU',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
function download(obj,name){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function copy(text,msg){navigator.clipboard?.writeText(text).then(()=>alert(msg)).catch(()=>prompt('Copy link',text))}
function currentRevision(p){return p?.revisions?.find(r=>r.id===p.currentRevisionId)||p?.revisions?.at(-1)||null}
function getActive(){return projects.find(p=>p.id===activeId)||null}
function renderList(){
  $('#projectCount').textContent=`${projects.length} PROJECT${projects.length===1?'':'S'}`;
  if(!projects.length){$('#projectList').innerHTML='<div class="empty-queue">No saved build projects yet. Save a concept in the configurator to create one.</div>';return;}
  if(!activeId||!projects.some(p=>p.id===activeId))activeId=projects[0].id;
  $('#projectList').innerHTML=projects.map(p=>{const r=currentRevision(p),s=r?.summary||{};return `<button class="project-card ${p.id===activeId?'active':''}" data-project="${esc(p.id)}"><div><b>${esc(p.title)}</b><span>${esc(p.id)}</span><span>${esc(s.vehicleLabel||'Y62 build')} · ${s.itemCount||0} items</span></div><div class="project-card-right"><b>${money(s.knownSubtotal||0)}</b><span>${esc(r?.id||'—')} · ${(p.revisions||[]).length} rev · v${p.version||0}</span></div></button>`}).join('');
  $$('[data-project]').forEach(b=>b.onclick=()=>{activeId=b.dataset.project;history.replaceState(null,'',`projects.html?project=${encodeURIComponent(activeId)}`);renderList();renderDetail()});
}
function renderDetail(){
  const p=getActive(),host=$('#projectDetail');if(!p){host.innerHTML='<div class="empty-queue">Select a saved build to inspect revision history.</div>';return;}
  const current=currentRevision(p),serverBacked=backend.mode!=='local-adapter';
  host.innerHTML=`<div class="eyebrow">${esc(p.id)}</div><h2>${esc(p.title)}</h2><div class="small">Created ${fmt(p.createdAt)} · updated ${fmt(p.updatedAt)} · persistence ${esc(backend.mode)}</div><div class="project-actions"><a class="primary link-button" href="index.html?project=${encodeURIComponent(p.id)}">OPEN CURRENT BUILD</a><button class="secondary" id="shareCustomer">CUSTOMER VIEW LINK</button><button class="secondary" id="shareStaff">STAFF REVIEW LINK</button><button class="secondary" id="exportProject">EXPORT PROJECT JSON</button></div><div class="local-share-warning">${serverBacked?'Server-backed project history is active. Share tokens can resolve from another device that can reach this Rig Builder server. Production identity/TLS are still pending.':'Browser-local fallback is active. Share links only resolve in this browser profile.'}</div><div class="staff-section"><div class="section-head"><h4>Revision history</h4><span class="mini-state">CURRENT ${esc(current?.id||'—')}</span></div><div class="revision-list">${[...(p.revisions||[])].reverse().map(r=>`<div class="revision-row ${r.id===p.currentRevisionId?'current':''}"><div><b>${esc(r.id)} · ${esc(r.summary?.leadName||'Saved concept')}</b><span>${fmt(r.createdAt)} · ${esc(r.source)} · checksum ${esc(r.checksum)}</span><span>${r.summary?.itemCount||0} items · ${money(r.summary?.knownSubtotal||0)} · ${esc(r.summary?.workflowStatus||'')}</span></div><div><button class="small-action" data-open-revision="${esc(r.id)}">OPEN</button><button class="small-action" data-restore-revision="${esc(r.id)}" ${r.id===p.currentRevisionId?'disabled':''}>SET CURRENT</button></div></div>`).join('')}</div></div><div class="staff-section"><h4>Active / previous share tokens</h4>${(p.shares||[]).length?`<div class="share-token-list">${[...(p.shares||[])].reverse().map(s=>`<div class="share-token-row"><div><b>${esc(s.role)} · ${esc(s.revisionId)}</b><span>••••${esc(s.tokenHint||'legacy')} · ${s.revokedAt?'REVOKED':s.expiresAt&&Date.parse(s.expiresAt)<Date.now()?'EXPIRED':'ACTIVE'} · created ${fmt(s.createdAt)}</span></div>${!s.revokedAt?`<button data-revoke="${esc(s.tokenHash||'')}" class="small-action">REVOKE</button>`:''}</div>`).join('')}</div>`:'<div class="empty-queue">No share tokens created.</div>'}</div>`;
  $('#exportProject').onclick=()=>download(p,`${p.id}.json`);$('#shareCustomer').onclick=()=>makeShare('customer-view');$('#shareStaff').onclick=()=>makeShare('staff-review');
  $$('[data-open-revision]').forEach(b=>b.onclick=()=>location.href=`index.html?project=${encodeURIComponent(p.id)}&revision=${encodeURIComponent(b.dataset.openRevision)}`);
  $$('[data-restore-revision]').forEach(b=>b.onclick=()=>restoreRevision(b.dataset.restoreRevision));
  $$('[data-revoke]').forEach(b=>b.onclick=()=>revokeShare(b.dataset.revoke));
}
async function refresh(preferredId=activeId){
  const host=$('#projectDetail');try{projects=await backend.listProjects();activeId=preferredId&&projects.some(p=>p.id===preferredId)?preferredId:(projects[0]?.id||null);renderList();renderDetail();}catch(e){projects=[];renderList();host.innerHTML=`<div class="empty-queue">Project service unavailable: ${esc(e.message)}</div>`}
}
async function makeShare(role){try{const p=getActive(),r=currentRevision(p);const s=await backend.createProjectShare(p.id,{role,revisionId:r?.id,expiresDays:30});const url=new URL('share.html',location.href);url.searchParams.set('token',s.token);copy(url.href,`${role==='staff-review'?'Staff review':'Customer view'} link copied.`);await refresh(p.id)}catch(e){alert(`Share creation failed: ${e.message}`)}}
async function restoreRevision(revisionId){try{const p=getActive();await backend.restoreProjectRevision(p.id,revisionId,{expectedVersion:p.version});await refresh(p.id)}catch(e){alert(e.code==='version_conflict'?`Project changed to version ${e.currentVersion}. Reloading first.`:`Revision restore failed: ${e.message}`);await refresh(activeId)}}
async function revokeShare(tokenHash){try{const p=getActive();await backend.revokeProjectShare(p.id,tokenHash);await refresh(p.id)}catch(e){alert(`Share revoke failed: ${e.message}`)}}
refresh();
