(async function(){
  const backend=window.PRO4X4_BACKEND.active(),plan=window.Y62_READINESS_PLAN,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let report=null;
  const pct=v=>v==null?'—':`${Math.round(v*1000)/10}%`;
  function statusLabel(x){return x==='slot-missing'?'SLOT MISSING':String(x||'unknown').replaceAll('-',' ').toUpperCase()}
  function statusClass(x){if(x==='production-ready')return 'ready';if(x==='candidate')return 'candidate';if(x==='blocked-fitment')return 'blocked';if(x==='reference-only')return 'reference';return 'missing'}
  function render(){if(!report)return;const s=report.summary,t=report.telemetry;
    $('readinessKpis').innerHTML=[['PLANNED CORE SLOTS',s.plannedSlots],['REGISTERED',s.registeredSlots],['MISSING SLOT RECORDS',s.missingSlots],['PRODUCTION READY',s.productionReadySlots],['COVERAGE',`${s.coveragePct}%`],['FRONT 3/4 CORE',`${s.front34ProductionReady}/${s.front34Planned}`]].map(([k,v])=>`<div class="card"><span class="eyebrow">${k}</span><b class="asset-kpi-value">${v}</b></div>`).join('');
    $('healthSummary').innerHTML=`<span class="readiness-dot ${esc(s.health)}"></span><div><b>${esc(s.health.toUpperCase())}</b><small>${esc(s.healthReason)}</small></div>`;
    const stateColumns=[...plan.paints.map(x=>({type:'paint',id:x.id,label:x.label})),...plan.wheelTyres.map(x=>({type:'wheelTyre',id:x.id,label:'Factory wheels'}))];
    let html=`<div class="readiness-grid header"><div>VIEW / CAMERA</div>${stateColumns.map(x=>`<div>${esc(x.label)}</div>`).join('')}</div>`;
    for(const view of report.views){html+=`<div class="readiness-grid"><div class="readiness-view"><b>${esc(view.label)}</b><span>${esc(view.cameraProfileId||'NO PROFILE')} · ${esc(view.cameraState)}</span><small>${view.productionReady}/${view.planned} production</small></div>`;for(const col of stateColumns){const cell=view.cells.find(c=>c.stateType===col.type&&c.stateId===col.id);if(!cell){html+='<div class="readiness-cell missing">NOT PLANNED</div>';continue}const link=cell.assetId?`asset-registry.html?assetId=${encodeURIComponent(cell.assetId)}`:null;html+=`<${link?'a':'div'} ${link?`href="${link}"`:''} class="readiness-cell ${statusClass(cell.status)}"><span>${statusLabel(cell.status)}</span><b>${esc(cell.stateKey)}</b><small>${esc(cell.assetId||'Create explicit slot')}</small><em>${esc(cell.nextAction)}</em></${link?'a':'div'}>`}html+='</div>'}
    $('readinessMatrix').innerHTML=html;
    $('telemetryHealth').innerHTML=`<div class="telemetry-kpis"><div><span>EVENTS</span><b>${t.eventCount}</b></div><div><span>LOAD SUCCESS</span><b>${t.loadSuccess}</b></div><div><span>LOAD ERRORS</span><b>${t.loadErrors}</b></div><div><span>RETRIES</span><b>${t.retries}</b></div><div><span>SUCCESS RATE</span><b>${pct(t.loadSuccessRate)}</b></div><div><span>RETRY RATE</span><b>${pct(t.retryRate)}</b></div></div><p class="small">Window: ${esc(t.windowHours)} hours. Green target: ≥ ${pct(t.thresholds.green.loadSuccessRateMin)} successful terminal loads and ≤ ${pct(t.thresholds.green.retryRateMax)} retry rate. No telemetry is treated as unknown, not healthy.</p>`;
    const pending=report.views.flatMap(v=>v.cells).filter(c=>!c.productionReady).sort((a,b)=>a.launchPriority-b.launchPriority).slice(0,8);$('nextDependencies').innerHTML=pending.map((c,i)=>`<div class="dependency-row"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(c.label)}</b><small>${esc(statusLabel(c.status))} · ${esc(c.nextAction)}</small></div>${c.assetId?`<a href="asset-registry.html?assetId=${encodeURIComponent(c.assetId)}">OPEN</a>`:''}</div>`).join('')||'<div class="validation-box ok">All validated core state slots are production-ready.</div>';
  }
  async function load(){try{report=await backend.getRenderReadiness(plan.vehicleId,24);render()}catch(e){$('healthSummary').innerHTML=`<div class="validation-box warn">Readiness unavailable: ${esc(e.message)}</div>`}}
  $('refreshReadiness').onclick=load;$('syncSlots').onclick=async()=>{const b=$('syncSlots');b.disabled=true;b.textContent='CREATING GOVERNED SLOTS…';try{const out=await backend.syncRenderReadinessSlots(plan.vehicleId);report=out.readiness;render();b.textContent=out.createdCount?`CREATED ${out.createdCount} STATE SLOTS`:'STATE SLOTS ALREADY SYNCED'}catch(e){b.textContent=`SYNC FAILED · ${e.message}`}finally{setTimeout(()=>{b.disabled=false;b.textContent='CREATE MISSING STATE SLOTS'},1800)}};await load();
})();
