const contract=window.PRO4X4_QUOTE_CONTRACT,projectStore=window.PRO4X4_PROJECT_STORE;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
if(window.PRO4X4_AUTH?.current?.().role==='customer')window.PRO4X4_AUTH.setLocalRole('sales','PRO4X4 Sales');
const backend=window.PRO4X4_BACKEND.active();let queueCache=[],settingsCache={labourRate:null,quoteValidityDays:14};
let filter='ALL',activeRef=null;const components=['parts','labour','paint','freight','engineering'];
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:Number(n)%1?2:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>String(v??'').trim()===''?null:Number(v);const clone=v=>JSON.parse(JSON.stringify(v));
function queue(){return queueCache}
function statusLabel(id){return contract.statuses.find(s=>s.id===id)?.label||id}
function readSettings(){return settingsCache}
function setMessage(text,error=false){const el=$('#settingsMessage');if(el){el.textContent=text;el.classList.toggle('error-copy',error)}}
function gateKey(g,i){return `${g.type||'gate'}:${g.id||i}:${i}`}
function ensureRecord(x){
  x=clone(x);x.schemaVersion=x.schemaVersion||'0.12.0';x.workflow=x.workflow||{status:'new',owner:null,staffNotes:'',lastUpdatedAt:new Date().toISOString()};
  x.selections=(x.selections||[]).map(a=>({...a,pricing:{parts:null,labour:null,paint:null,freight:null,engineering:null,...(a.pricing||{})},pricingRequired:Array.isArray(a.pricingRequired)?a.pricingRequired:components}));
  x.fitmentReview=x.fitmentReview||{resolutions:[]};const old=new Map((x.fitmentReview.resolutions||[]).map(r=>[r.key,r]));
  x.fitmentReview.resolutions=(x.gates||[]).map((g,i)=>{const key=gateKey(g,i);return old.get(key)||{key,type:g.type,id:g.id,status:'unresolved',staffNote:'',sourceNote:g.note}});
  x.quoteFinalisation=x.quoteFinalisation||{status:'draft',quoteNumber:null,issuedAt:null,validUntil:null,customerTotal:null,labourRateUsed:null};recompute(x);return x;
}
function recompute(x){
  const totals={parts:0,labour:0,paint:0,freight:0,engineering:0},missing={parts:0,labour:0,paint:0,freight:0,engineering:0};
  (x.selections||[]).forEach(a=>components.forEach(k=>{const v=a.pricing?.[k],required=(a.pricingRequired||components).includes(k);if(v==null){if(required)missing[k]++}else totals[k]+=Number(v)||0}));
  x.pricing=x.pricing||{};x.pricing.currency='AUD';x.pricing.components=totals;x.pricing.unpricedComponentCounts=missing;x.pricing.knownSubtotal=components.reduce((n,k)=>n+totals[k],0);x.pricing.isComplete=components.every(k=>missing[k]===0);
  const knownMass=(x.selections||[]).reduce((n,a)=>n+(Number.isFinite(Number(a.weightKg))?Number(a.weightKg):0),0),unknownMass=(x.selections||[]).filter(a=>a.weightKg==null).length,base=x.weight?.baseline||null;
  x.weight={...(x.weight||{}),baseline:base,knownAccessoryMassKg:Number(knownMass.toFixed(2)),unknownAccessoryMassCount:unknownMass};if(base?.kerbMassKg!=null&&base?.gvmKg!=null){x.weight.estimatedKerbMassWithKnownAccessoriesKg=Number((base.kerbMassKg+knownMass).toFixed(2));x.weight.remainingNominalPayloadKg=Number((base.gvmKg-base.kerbMassKg-knownMass).toFixed(2));}
  const res=x.fitmentReview?.resolutions||[];x.fitmentReview.allApproved=res.length===0||res.every(r=>r.status==='approved');x.fitmentReview.hasRejected=res.some(r=>r.status==='rejected');if(!['quoted','won','lost'].includes(x.workflow.status))x.workflow.status=!x.fitmentReview.allApproved?'needs-fitment-review':!x.pricing.isComplete?'pricing-incomplete':'ready-to-quote';return x;
}
function upsertCache(record){const x=ensureRecord(record),i=queueCache.findIndex(v=>v.reference===x.reference);if(i>=0)queueCache[i]=x;else queueCache.unshift(x);return x}
async function refreshQueue(){try{queueCache=(await backend.listQuotes()).map(ensureRecord);if(activeRef&&!queueCache.some(x=>x.reference===activeRef))activeRef=null;renderQueue();renderDetail();}catch(e){$('#queue').innerHTML=`<div class="empty-queue">Backend unavailable: ${esc(e.message)}</div>`;$('#detail').innerHTML='<div class="empty-queue">Run the Alpha 12 local server or use ?backend=local.</div>'}}
async function loadSettings(){try{settingsCache={...settingsCache,...await backend.getStaffSettings()};$('#labourRate').value=settingsCache.labourRate??'';$('#quoteDays').value=settingsCache.quoteValidityDays??14;setMessage(`Backend: ${backend.mode}`);}catch(e){setMessage(`Settings unavailable: ${e.message}`,true)}}
async function saveSettings(){const rate=num($('#labourRate').value),days=Math.max(1,Math.round(Number($('#quoteDays').value)||14));try{settingsCache=await backend.setStaffSettings({labourRate:rate,quoteValidityDays:days});setMessage(rate==null?'Saved. Labour suggestions remain disabled until a workshop rate is entered.':`Saved · ${money(rate)}/hr · quotes ${days} days.`);renderDetail()}catch(e){setMessage(`Save failed: ${e.message}`,true)}}
function renderKpis(q){$('#kpiTotal').textContent=q.length;$('#kpiFitment').textContent=q.filter(x=>x.workflow.status==='needs-fitment-review').length;$('#kpiPricing').textContent=q.filter(x=>x.workflow.status==='pricing-incomplete').length;$('#kpiReady').textContent=q.filter(x=>x.workflow.status==='ready-to-quote').length}
function renderQueue(){const q=queue();renderKpis(q);const host=$('#queue'),rows=q.filter(x=>filter==='ALL'||x.workflow.status===filter);if(!rows.length){host.innerHTML='<div class="empty-queue">No builds in this queue state yet.</div>';return;}host.innerHTML='';rows.forEach(x=>{const el=document.createElement('article');el.className='queue-item '+(activeRef===x.reference?'active':'');const ready=x.fitmentReview.allApproved&&x.pricing.isComplete;el.innerHTML=`<div><h3>${esc(x.lead?.name||'Unnamed concept')}</h3><div class="queue-meta">${esc(x.reference)} · ${esc(x.vehicle?.make||'')} ${esc(x.vehicle?.model||'')} · ${x.selections.length} items · ${money(x.pricing.knownSubtotal)}</div><div class="queue-meta">${ready?'QUOTE GATE CLEAR':'REVIEW REQUIRED'} · catalogue ${esc(x.catalogue?.revision||'legacy')}</div></div><span class="queue-badge">${esc(statusLabel(x.workflow.status))}</span>`;el.onclick=()=>{activeRef=x.reference;renderQueue();renderDetail()};host.appendChild(el)})}
function suggestedLabour(a){const rate=readSettings().labourRate,h=a.install?.estimateHoursMax??a.install?.estimateHoursMin;if(rate==null||h==null)return null;return Number((Number(rate)*Number(h)).toFixed(2))}
function priceMatrix(x){return `<div class="quote-lines">${x.selections.map(a=>`<div class="quote-line-editor"><div class="line-title"><b>${esc(a.name)}</b><span>${esc(a.brand)} · ${esc(a.sku)}</span></div><div class="line-prices">${components.map(k=>{const req=(a.pricingRequired||components).includes(k),v=a.pricing?.[k];return `<label class="price-cell ${req?'required':'optional'}"><span>${k}${req?' *':''}</span><input data-price-id="${esc(a.id)}" data-price-component="${k}" type="number" min="0" step="0.01" value="${v??''}" placeholder="${req?'QUOTE':'N/A'}"></label>`}).join('')}</div>${suggestedLabour(a)!=null&&a.pricing?.labour==null?`<button class="suggest-labour" data-suggest-labour="${esc(a.id)}">USE ${a.install.estimateHoursMax??a.install.estimateHoursMin}HR × RATE = ${money(suggestedLabour(a))}</button>`:''}</div>`).join('')}</div>`}
function gateEditor(x){if(!(x.gates||[]).length)return '<div class="clean-state">No fitment gates.</div>';return `<div class="gate-review-list">${x.gates.map((g,i)=>{const r=x.fitmentReview.resolutions[i];return `<div class="gate-review"><div><b>${esc(g.note)}</b><span>${esc(g.type)} · ${esc(g.id)}</span></div><select data-gate-status="${i}"><option value="unresolved" ${r.status==='unresolved'?'selected':''}>Unresolved</option><option value="approved" ${r.status==='approved'?'selected':''}>Approved / resolved</option><option value="rejected" ${r.status==='rejected'?'selected':''}>Rejected</option></select><input data-gate-note="${i}" value="${esc(r.staffNote||'')}" placeholder="Staff resolution / evidence"></div>`}).join('')}</div>`}
function weightPanel(x){const w=x.weight||{},b=w.baseline||{};return `<div class="weight-grid"><div><span>KNOWN ACCESSORY MASS</span><b>${w.knownAccessoryMassKg||0} kg</b></div><div><span>UNKNOWN WEIGHT ITEMS</span><b>${w.unknownAccessoryMassCount||0}</b></div><div><span>PLANNING KERB</span><b>${w.estimatedKerbMassWithKnownAccessoriesKg!=null?`${w.estimatedKerbMassWithKnownAccessoriesKg} kg`:'—'}</b></div><div><span>REMAINING NOMINAL PAYLOAD</span><b>${w.remainingNominalPayloadKg!=null?`${w.remainingNominalPayloadKg} kg`:'—'}</b></div></div><div class="small warning-copy">${esc(b.note||'Accessory mass is a planning aid only. Confirm exact vehicle, axle loads, passengers, cargo and towball download before compliance sign-off.')}</div>`}
function renderDetail(){const x=queue().find(v=>v.reference===activeRef),host=$('#detail');if(!x){host.innerHTML='<div class="empty-queue">Select a build submission to inspect the quote handoff.</div>';return;}const missing=Object.entries(x.pricing.unpricedComponentCounts).filter(([,v])=>v>0),ready=x.fitmentReview.allApproved&&x.pricing.isComplete;host.innerHTML=`<div class="eyebrow">${esc(x.reference)} · ${esc(backend.mode)}</div><h2>${esc(x.lead?.name||'Unnamed concept')}</h2><div class="small">${esc(x.lead?.phone||'No phone')} · ${esc(x.lead?.email||'No email')} · ${esc(x.lead?.postcode||'No postcode')}</div>
<div class="staff-section"><h4>Vehicle / build</h4><div class="staff-line"><span>Vehicle</span><b>${esc(x.vehicle?.make)} ${esc(x.vehicle?.model)} ${esc(x.vehicle?.trim||'')}</b></div><div class="staff-line"><span>Paint</span><b>${esc(x.vehicle?.paint)}</b></div><div class="staff-line"><span>Project</span><b>${x.project?.id?`${esc(x.project.id)} · ${esc(x.project.revisionId||'')}`:'Legacy / unversioned'}</b></div><div class="staff-line"><span>Catalogue</span><b>${esc(x.catalogue?.revision||'legacy / base')}</b></div><div class="staff-line"><span>Render ready</span><b>${x.render?.productionReady?'YES':'NO'}</b></div></div>
<div class="staff-section"><div class="section-head"><h4>Weight / payload planning</h4><span class="mini-state">PLANNING ONLY</span></div>${weightPanel(x)}</div>
<div class="staff-section"><h4>Fitment / engineering sign-off</h4>${gateEditor(x)}</div>
<div class="staff-section"><div class="section-head"><h4>Required-component pricing</h4><span class="mini-state ${x.pricing.isComplete?'confirmed':'engineering'}">${x.pricing.isComplete?'COMPLETE':'OPEN ITEMS'}</span></div><div class="small">Only catalogue components marked required block quote readiness. Blank optional fields are treated as not applicable, not as $0.</div>${priceMatrix(x)}<div class="quote-total"><span>Known / resolved total</span><b>${money(x.pricing.knownSubtotal)}</b></div>${missing.length?`<div class="small warning-copy">Still required: ${missing.map(([k,v])=>`${k} ×${v}`).join(' · ')}</div>`:'<div class="clean-state">Required pricing gate clear.</div>'}</div>
<div class="staff-section"><h4>Workflow</h4><div class="staff-controls"><select id="staffStatus">${contract.statuses.map(s=>`<option value="${s.id}" ${x.workflow.status===s.id?'selected':''}>${s.label}</option>`).join('')}</select><input id="staffOwner" placeholder="Owner / salesperson" value="${esc(x.workflow.owner||'')}"></div><textarea id="staffNotes" class="staff-note" placeholder="Internal fitment / pricing notes">${esc(x.workflow.staffNotes||'')}</textarea><div class="readiness-banner ${ready?'ready':'blocked'}"><b>${ready?'FORMAL QUOTE GATE CLEAR':'FORMAL QUOTE BLOCKED'}</b><span>${ready?'All fitment gates approved and required pricing resolved.':'Resolve fitment gates and required pricing before finalisation.'}</span></div><div class="staff-actions wrap-actions"><button class="primary" id="saveWorkflow">SAVE REVIEW</button><button class="secondary" id="previewQuote">QUOTE PREVIEW</button><button class="primary" id="finaliseQuote" ${ready?'':'disabled'}>FINALISE QUOTE</button><button class="secondary" id="exportRecord">EXPORT JSON</button></div></div>`;
$('#saveWorkflow').onclick=()=>updateRecord(x.reference,true);$('#previewQuote').onclick=()=>openQuote(x.reference,false);$('#finaliseQuote').onclick=()=>openQuote(x.reference,true);$('#exportRecord').onclick=()=>download(x);$$('[data-suggest-labour]').forEach(b=>b.onclick=()=>applyLabour(x.reference,b.dataset.suggestLabour));}
function collectDetail(x){$$('[data-price-id]').forEach(i=>{const a=x.selections.find(v=>v.id===i.dataset.priceId);if(a)a.pricing[i.dataset.priceComponent]=num(i.value)});(x.fitmentReview.resolutions||[]).forEach((r,i)=>{r.status=$(`[data-gate-status="${i}"]`)?.value||r.status;r.staffNote=$(`[data-gate-note="${i}"]`)?.value.trim()||''});x.workflow.owner=$('#staffOwner')?.value.trim()||null;x.workflow.staffNotes=$('#staffNotes')?.value.trim()||'';x.workflow.lastUpdatedAt=new Date().toISOString();recompute(x);const manual=$('#staffStatus')?.value;if(manual&&['quoted','won','lost'].includes(manual))x.workflow.status=manual;}
function commitLocalProjectRevision(x,source){if(backend.mode!=='local-adapter'||!x.project?.id)return x;try{const saved=projectStore.saveRevision(x,{projectId:x.project.id,title:x.lead?.name?`${x.lead.name} · Y62 Warrior`:'Y62 Warrior Build',source});return ensureRecord(saved.snapshot)}catch{return x}}
async function updateRecord(ref,rerender){let x=queue().find(v=>v.reference===ref);if(!x)return;collectDetail(x);x=commitLocalProjectRevision(x,'staff-review-save');try{x=ensureRecord(await backend.updateQuote(ref,x));upsertCache(x);if(rerender){renderQueue();renderDetail()}}catch(e){alert(`Save failed: ${e.message}`)}}
async function applyLabour(ref,id){let x=queue().find(v=>v.reference===ref),a=x?.selections.find(v=>v.id===id);if(!x||!a)return;const suggestion=suggestedLabour(a);if(suggestion==null)return;a.pricing.labour=suggestion;recompute(x);x.workflow.lastUpdatedAt=new Date().toISOString();try{x=ensureRecord(await backend.updateQuote(ref,x));upsertCache(x);renderQueue();renderDetail()}catch(e){alert(`Labour update failed: ${e.message}`)}}
async function openQuote(ref,finalise){let x=queue().find(v=>v.reference===ref);if(!x)return;collectDetail(x);const ready=x.fitmentReview.allApproved&&x.pricing.isComplete;if(finalise&&!ready){renderQueue();renderDetail();return;}try{x=ensureRecord(await backend.updateQuote(ref,x));if(finalise)x=ensureRecord(await backend.finaliseQuote(ref,{}));upsertCache(x);if(backend.mode==='local-adapter')window.PRO4X4_SALES_STORE?.setPreview(x);renderQueue();renderDetail();window.open(`quote.html?ref=${encodeURIComponent(x.reference)}${backend.mode==='local-adapter'?'&backend=local':''}`,'_blank')}catch(e){alert(`Quote ${finalise?'finalisation':'preview'} failed: ${e.message}`)}}
function download(payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${payload.reference}-staff.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderQueue()});$('#saveSettings').onclick=saveSettings;
Promise.all([loadSettings(),refreshQueue()]);
