const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
if(window.PRO4X4_AUTH?.current?.().role==='customer')window.PRO4X4_AUTH.setLocalRole('admin','PRO4X4 Admin');
const backend=window.PRO4X4_BACKEND.active();let events=[],integrity=null;
function fmt(d){try{return new Date(d).toLocaleString('en-AU',{dateStyle:'medium',timeStyle:'short'})}catch{return d||'—'}}
function shortHash(x){return x?`${String(x).slice(0,12)}…`:'—'}
function integrityClass(status){return status==='sealed'?'ok':status==='sealed-with-legacy-prefix'?'warn':status==='broken'?'bad':'neutral'}
function renderIntegrity(){const host=$('#auditIntegrity');if(!integrity){host.innerHTML='<div class="audit-integrity-card neutral"><b>LEDGER INTEGRITY</b><span>Verification unavailable.</span></div>';return}const cls=integrityClass(integrity.status),label=String(integrity.status||'unknown').replaceAll('-',' ').toUpperCase(),problems=integrity.problems||[];host.innerHTML=`<div class="audit-integrity-card ${cls}"><div><span class="eyebrow">AUDIT / PRODUCTION CONTROL</span><b>${esc(label)}</b><small>${esc(integrity.policy||'append-only ledger')} · checked ${esc(fmt(integrity.checkedAt))}</small></div><div class="audit-integrity-stats"><span><b>${integrity.sealedEvents||0}</b> sealed</span><span><b>${integrity.legacyEvents||0}</b> legacy</span><span><b>${integrity.totalEvents||0}</b> total</span></div><div class="audit-integrity-head"><span>HEAD SHA-256</span><code>${esc(integrity.headHash||'NO SEALED EVENTS')}</code></div></div>${problems.length?`<div class="audit-integrity-problems"><b>INTEGRITY BLOCKERS</b>${problems.slice(0,8).map(p=>`<span>${esc(p.code)}${p.id?` · ${esc(p.id)}`:''}</span>`).join('')}</div>`:''}`}
function governanceEvidence(e){const m=e.metadata||{},r=m.reviewEvidence||m.approval?.reviewEvidence||null;if(e.entityType!=='render-asset')return '';const assetLink=`asset-registry.html?assetId=${encodeURIComponent(e.entityId||'')}`,bits=[];if(m.versionId)bits.push(`VERSION ${esc(m.versionId)}`);if(r?.reviewedBy)bits.push(`REVIEWER ${esc(r.reviewedBy)}`);if(r?.reviewedAt)bits.push(`REVIEWED ${esc(fmt(r.reviewedAt))}`);if(r?.checksumSha256)bits.push(`SHA ${esc(shortHash(r.checksumSha256))}`);if(r?.licenceStatus)bits.push(`RIGHTS ${esc(String(r.licenceStatus).toUpperCase())}`);return `<div class="audit-governance"><a href="${assetLink}">OPEN GOVERNED ASSET →</a>${bits.map(x=>`<span>${x}</span>`).join('')}</div>`}
function render(){const entity=$('#auditEntity').value,q=$('#auditSearch').value.trim().toLowerCase(),rows=events.filter(e=>(!entity||e.entityType===entity)&&(!q||JSON.stringify(e).toLowerCase().includes(q)));$('#auditSummary').innerHTML=`<span><b>${rows.length}</b> shown</span><span><b>${events.length}</b> loaded</span><span>Backend <b>${esc(backend.mode)}</b></span><span>Chain <b>${esc(integrity?.integrityVersion||'unavailable')}</b></span>`;const host=$('#auditList');if(!rows.length){host.innerHTML='<div class="empty-queue">No matching audit events yet.</div>';return;}host.innerHTML=rows.map(e=>{const sealed=!!e.integrity?.eventHash;return `<article class="audit-row"><div class="audit-time">${esc(fmt(e.at))}</div><div class="audit-main"><div class="audit-action">${esc(e.action)} <span class="audit-seal ${sealed?'sealed':'legacy'}">${sealed?'SEALED':'LEGACY'}</span></div><div class="audit-meta">${esc(e.entityType)} · ${esc(e.entityId||'—')} · ${esc(e.actor?.displayName||e.actor?.actorId||'unknown')} (${esc(e.actor?.role||'unknown')})</div>${governanceEvidence(e)}<pre>${esc(JSON.stringify(e.metadata||{},null,2))}</pre>${sealed?`<div class="audit-hashline"><span>PREV ${esc(shortHash(e.integrity.previousHash))}</span><span>EVENT ${esc(shortHash(e.integrity.eventHash))}</span></div>`:''}</div><div class="audit-id">${esc(e.id)}</div></article>`}).join('')}
async function refresh(){const host=$('#auditList');host.innerHTML='<div class="empty-queue">Loading audit trail…</div>';try{const out=await Promise.all([backend.listAudit({limit:500}),backend.getAuditIntegrity?backend.getAuditIntegrity():Promise.resolve(null)]);events=out[0]||[];integrity=out[1];renderIntegrity();render()}catch(e){host.innerHTML=`<div class="empty-queue">Audit backend unavailable: ${esc(e.message)}</div>`;integrity=null;renderIntegrity()}}
$('#auditEntity').onchange=render;$('#auditSearch').oninput=render;$('#auditRefresh').onclick=refresh;refresh();
