(function(){
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const json=(status,body)=>({ok:status>=200&&status<300,status,async json(){return body==null?null:JSON.parse(JSON.stringify(body))}});
  const err=(status,code,message,fieldErrors=[])=>json(status,{error:code,code,message,fieldErrors,requestId:`MOCK-${Date.now().toString(36).toUpperCase()}`});
  function parse(url){const u=new URL(url,location.origin);return {path:u.pathname.replace(/^\/api\/v1/,'')||'/',search:u.searchParams}}
  function role(){return window.PRO4X4_AUTH?.current?.()?.role||'customer'}
  function staff(){return ['sales','fitment','admin'].includes(role())}
  function admin(){return role()==='admin'}
  function validateBuild(x){const f=[];if(!x||typeof x!=='object')f.push({field:'body',message:'Build payload is required'});if(!x?.reference||!/^P4X4-/.test(x.reference))f.push({field:'reference',message:'Reference must begin P4X4-'});if(!x?.vehicle?.id)f.push({field:'vehicle.id',message:'Vehicle ID is required'});if(!Array.isArray(x?.selections))f.push({field:'selections',message:'Selections must be an array'});return f}
  function validateCatalogue(x,vehicleId){const f=[];if(!x||typeof x!=='object')f.push({field:'body',message:'Catalogue snapshot is required'});if(x?.vehicleId&&x.vehicleId!==vehicleId)f.push({field:'vehicleId',message:'Vehicle ID does not match route'});if(!Array.isArray(x?.accessories))f.push({field:'accessories',message:'Accessories must be an array'});return f}
  async function sealQuote(payload,projects){const x=JSON.parse(JSON.stringify(payload||{})),pid=x.project?.id||null,rid=x.project?.revisionId||null,sealedAt=new Date().toISOString(),sealedBy=window.PRO4X4_AUTH?.actorSnapshot?.()||null;if(pid||rid){if(!pid||!rid)throw Object.assign(new Error('Quote project lineage requires both project ID and revision ID'),{code:'quote_lineage_invalid'});const project=projects.getProject(pid),revision=project?.revisions?.find(r=>r.id===rid);if(!project||!revision)throw Object.assign(new Error('Linked immutable project revision was not found'),{code:'quote_lineage_invalid'});if(revision.snapshot?.reference&&revision.snapshot.reference!==x.reference)throw Object.assign(new Error('Quote reference does not match the linked saved revision'),{code:'quote_lineage_invalid'});x.project=JSON.parse(JSON.stringify(revision.snapshot.project||x.project));x.quoteLineage={schemaVersion:'0.26.9',policy:'immutable-project-revision',sourceProjectId:pid,sourceRevisionId:rid,sourceRevisionChecksum:revision.checksum,submittedSnapshotChecksum:await projects.sha256(JSON.stringify(payload||{})),sealedAt,sealedBy}}const seal=window.PRO4X4_QUOTE_VISUAL_GOVERNANCE_SEAL,assets=window.PRO4X4_ASSET_REGISTRY?.load?.()||[];if(seal)x.visualGovernanceSeal=seal.seal({quote:x,assets,versionsByAsset:{},sealedAt,sealedBy});return x}
  function preserveQuoteLineage(existing,payload){const a=existing?.project||{},b=payload?.project||{},seal=window.PRO4X4_QUOTE_VISUAL_GOVERNANCE_SEAL;if((a.id||null)!==(b.id||null)||(a.revisionId||null)!==(b.revisionId||null))throw Object.assign(new Error('Quote source project/revision is immutable after submission'),{code:'quote_lineage_immutable'});if(seal&&seal.renderHash(existing?.render)!==seal.renderHash(payload?.render))throw Object.assign(new Error('Quote render snapshot is immutable after visual-governance sealing'),{code:'quote_visual_lineage_immutable'});return {...payload,project:existing?.project||null,quoteLineage:existing?.quoteLineage||null,visualGovernanceSeal:existing?.visualGovernanceSeal||null}}
  async function fetcher(url,opts={}){
    await sleep(15);const {path,search}=parse(url),method=(opts.method||'GET').toUpperCase();let body=null;try{body=opts.body?JSON.parse(opts.body):null}catch{return err(400,'invalid_json','Request body is not valid JSON')}
    const projects=window.PRO4X4_PROJECT_STORE,sales=window.PRO4X4_SALES_STORE,catalogue=window.PRO4X4_CATALOGUE_STORE,audit=window.PRO4X4_AUDIT_STORE;
    let m;
    if(method==='GET'&&path==='/health')return json(200,{ok:true,schemaVersion:'0.12.0',service:'mock-api',authMode:'prototype-mock',dbSchemaVersion:null});
    if(method==='GET'&&path==='/auth/session'){const a=window.PRO4X4_AUTH.current();return json(200,{schemaVersion:'0.12.0',authenticated:true,source:'prototype-mock',actor:a,expiresAt:null,capabilities:{devLogin:true,prototypeHeaders:true},production:false})}
    if(method==='POST'&&path==='/auth/dev-login'){try{const a=window.PRO4X4_AUTH.setLocalRole(body?.role||'customer',body?.displayName);return json(201,{schemaVersion:'0.12.0',authenticated:true,source:'prototype-mock',actor:a,expiresAt:null,production:false})}catch(e){return err(422,'validation_error',e.message)}}
    if(method==='POST'&&path==='/auth/logout'){window.PRO4X4_AUTH.setLocalRole('customer','Local Customer');return json(200,{schemaVersion:'0.12.0',loggedOut:true})}
    if(method==='POST'&&path==='/builds'){const fields=validateBuild(body);if(fields.length)return err(422,'validation_error','Build payload failed validation',fields);try{const sealed=await sealQuote({...body,schemaVersion:'0.12.0'},projects),saved=sales.upsert(sealed,{action:'quote.submitted',metadata:{via:'mock-api'}});return json(201,saved)}catch(e){return err(['quote_lineage_immutable','quote_visual_lineage_immutable'].includes(e.code)?409:422,e.code||'quote_lineage_invalid',e.message)}}
    if(method==='POST'&&path==='/render/resolve'){const manifest=window.Y62_RENDER_MANIFEST,view=manifest?.views?.[body?.viewId],layers=(body?.requirements||[]).map(r=>{const skuMatches=view?.layers?.filter(x=>x.id===r.layerId&&(x.exactSku||null)===(r.exactSku||null))||[],m=skuMatches.find(x=>Object.entries(r.state||{}).every(([k,v])=>x.renderState?.[k]===v)),blocked=m?.status==='blocked-fitment',reason=!m&&skuMatches.length&&Object.keys(r.state||{}).length?'render-state-not-registered':blocked?'fitment-blocked':'mock-has-no-governed-production-binary';return {layerId:r.layerId,exactSku:r.exactSku??null,stateKey:r.stateKey||null,requestedState:r.state||{},state:blocked?'blocked':'missing',reason,registryStatus:m?.status||null,assetId:null,binaryUrl:null,checksumSha256:null}}),counts={available:0,missing:layers.filter(x=>x.state==='missing').length,blocked:layers.filter(x=>x.state==='blocked').length};return json(200,{schemaVersion:'0.22.0',vehicleId:body?.vehicleId||null,viewId:body?.viewId||null,fallbackPolicy:'none',exactMatchRequired:true,productionReady:false,counts,layers,source:'prototype-mock-unverified'})}
    if(path==='/staff/quotes'&&!staff())return err(403,'forbidden','Staff role required');
    if(method==='GET'&&path==='/staff/quotes')return json(200,sales.list());
    if(method==='GET'&&(m=path.match(/^\/staff\/quotes\/([^/]+)$/))){if(!staff())return err(403,'forbidden','Staff role required');const x=sales.get(decodeURIComponent(m[1]));return x?json(200,x):err(404,'not_found','Quote not found')}
    if(method==='GET'&&(m=path.match(/^\/staff\/quotes\/([^/]+)\/lineage$/))){if(!staff())return err(403,'forbidden','Staff role required');const reference=decodeURIComponent(m[1]),quote=sales.get(reference);if(!quote)return err(404,'not_found','Quote not found');const project=quote.project?.id?projects.getProject(quote.project.id):null,events=audit.list({limit:500}),out=window.PRO4X4_STAFF_LINEAGE.inspect({quote,project,assets:window.PRO4X4_ASSET_REGISTRY?.load?.()||[],versionsByAsset:{},quoteEvents:events.filter(e=>e.entityType==='quote'&&e.entityId===reference).slice(0,20),projectEvents:project?events.filter(e=>e.entityType==='project'&&e.entityId===project.id).slice(0,20):[]});return json(200,out)}
    if(method==='PATCH'&&(m=path.match(/^\/staff\/quotes\/([^/]+)$/))){if(!staff())return err(403,'forbidden','Staff role required');const reference=decodeURIComponent(m[1]),existing=sales.get(reference);if(!existing)return err(404,'not_found','Quote not found');if(body?.reference&&body.reference!==reference)return err(422,'validation_error','Reference mismatch',[{field:'reference',message:'Body reference must match route'}]);try{const saved=sales.upsert(preserveQuoteLineage(existing,{...existing,...body,reference,schemaVersion:'0.12.0'}),{action:'quote.updated',metadata:{via:'mock-api'}});return json(200,saved)}catch(e){return err(409,e.code||'quote_lineage_immutable',e.message)}}
    if(method==='POST'&&(m=path.match(/^\/staff\/quotes\/([^/]+)\/finalise$/))){if(!staff())return err(403,'forbidden','Staff role required');const reference=decodeURIComponent(m[1]),existing=sales.get(reference);if(!existing)return err(404,'not_found','Quote not found');if(!existing.pricing?.isComplete||!existing.fitmentReview?.allApproved)return err(409,'quote_gate_blocked','Quote cannot be finalised until pricing and fitment gates are clear');const saved=sales.upsert({...existing,quoteFinalisation:{...(existing.quoteFinalisation||{}),...(body||{}),status:'finalised'}},{action:'quote.finalised',metadata:{via:'mock-api'}});return json(200,saved)}
    if(method==='GET'&&path==='/staff/settings/quote'){if(!staff())return err(403,'forbidden','Staff role required');return json(200,sales.getSettings())}
    if(method==='PATCH'&&path==='/staff/settings/quote'){if(!staff())return err(403,'forbidden','Staff role required');return json(200,sales.setSettings(body||{}))}
    if(method==='GET'&&(m=path.match(/^\/catalogue\/([^/]+)$/))){const vehicleId=decodeURIComponent(m[1]),c=catalogue.getPublished()||catalogue.base();return c.vehicleId===vehicleId?json(200,c):err(404,'not_found','Catalogue not found')}
    if(method==='POST'&&(m=path.match(/^\/staff\/catalogue\/([^/]+)\/revisions$/))){if(!staff())return err(403,'forbidden','Staff role required');const vehicleId=decodeURIComponent(m[1]),fields=validateCatalogue(body,vehicleId);if(fields.length)return err(422,'validation_error','Catalogue failed validation',fields);const out=catalogue.publish({...body,vehicleId},window.PRO4X4_AUTH?.current?.()?.displayName||'PRO4X4 staff');return json(201,out)}
    if(method==='GET'&&(m=path.match(/^\/staff\/catalogue\/([^/]+)\/draft$/))){if(!staff())return err(403,'forbidden','Staff role required');return json(200,catalogue.getDraft())}
    if(method==='PUT'&&(m=path.match(/^\/staff\/catalogue\/([^/]+)\/draft$/))){if(!staff())return err(403,'forbidden','Staff role required');return json(200,catalogue.saveDraft(body||{}))}
    if(method==='DELETE'&&(m=path.match(/^\/staff\/catalogue\/([^/]+)\/draft$/))){if(!staff())return err(403,'forbidden','Staff role required');catalogue.discardDraft();return json(204,null)}
    if(method==='GET'&&path==='/staff/audit'){if(!staff())return err(403,'forbidden','Staff role required');return json(200,audit.list({entityType:search.get('entityType'),entityId:search.get('entityId'),action:search.get('action'),limit:search.get('limit')||200}))}
    if(method==='GET'&&path==='/staff/audit/integrity'){if(!staff())return err(403,'forbidden','Staff role required');return json(200,audit.verify())}
    if(method==='GET'&&path==='/admin/backup'){if(!admin())return err(403,'forbidden','Admin role required');const entries={};window.PRO4X4_PERSISTENCE.local.keys().forEach(k=>entries[k]=window.PRO4X4_PERSISTENCE.local.get(k,null));return json(200,{schemaVersion:'0.12.0',exportedAt:new Date().toISOString(),mode:'mock-localStorage',entries})}
    if(method==='POST'&&path==='/admin/backup/restore'){if(!admin())return err(403,'forbidden','Admin role required');if(!body?.entries)return err(422,'validation_error','Backup entries missing',[{field:'entries',message:'entries is required'}]);Object.entries(body.entries).forEach(([k,v])=>window.PRO4X4_PERSISTENCE.local.set(k,v));return json(200,{schemaVersion:'0.12.0',restored:true,entryCount:Object.keys(body.entries).length})}
    if(method==='POST'&&path==='/admin/import/seed'){if(!admin())return err(403,'forbidden','Admin role required');if(body?.schemaVersion!=='0.12.0')return err(422,'validation_error','Seed bundle schemaVersion must be 0.12.0',[{field:'schemaVersion',message:'Expected 0.12.0'}]);const report={catalogues:0,quotes:0,projects:0,errors:[]};try{if(body.catalogue){catalogue.publish(body.catalogue,'Seed Import');report.catalogues++}}catch(e){report.errors.push(`catalogue: ${e.message}`)};(body.quotes||[]).forEach((q,i)=>{try{sales.upsert({...q,schemaVersion:'0.12.0'},{action:'seed.quote.imported'});report.quotes++}catch(e){report.errors.push(`quote ${i+1}: ${e.message}`)}});(body.projectSnapshots||[]).forEach((s,i)=>{try{projects.saveRevision({...s,schemaVersion:'0.12.0',contract:{...(s.contract||{}),version:'0.12.0'}},{title:s.lead?.name?`${s.lead.name} · Seed Build`:'Seed Build',source:'seed-import'});report.projects++}catch(e){report.errors.push(`project ${i+1}: ${e.message}`)}});audit.append('seed.import.completed','system','seed',{report});return json(report.errors.length?207:201,report)}
    if(method==='GET'&&path==='/projects')return json(200,projects.listProjects());
    if(method==='GET'&&(m=path.match(/^\/projects\/([^/]+)$/))){const p=projects.getProject(decodeURIComponent(m[1]));return p?json(200,p):err(404,'not_found','Project not found')}
    if(method==='PUT'&&(m=path.match(/^\/projects\/([^/]+)\/current-revision$/))){try{const projectId=decodeURIComponent(m[1]),snapshot=projects.restoreRevision(projectId,body.revisionId,{expectedVersion:body.expectedVersion});return snapshot?json(200,{project:projects.getProject(projectId),snapshot}):err(404,'not_found','Project/revision not found')}catch(e){return err(e.code==='VERSION_CONFLICT'?409:400,e.code||'bad_request',e.message)}}
    if(method==='POST'&&(m=path.match(/^\/projects\/([^/]+)\/revisions$/))){try{const saved=projects.saveRevision(body.snapshot||body,{projectId:decodeURIComponent(m[1]),source:body.source||'mock-api',expectedVersion:body.expectedVersion});return json(201,saved)}catch(e){return err(e.code==='VERSION_CONFLICT'?409:400,e.code||'bad_request',e.message)}}
    if(method==='POST'&&(m=path.match(/^\/projects\/([^/]+)\/shares$/))){try{return json(201,await projects.createShare(decodeURIComponent(m[1]),body.role,body.revisionId,body.expiresDays))}catch(e){return err(400,'bad_request',e.message)}}
    if(method==='DELETE'&&(m=path.match(/^\/projects\/([^/]+)\/shares\/([a-f0-9]{64})$/i))){const ok=await projects.revokeShare(m[2]);return ok?json(204,null):err(404,'not_found','Share not found')}
    if(method==='GET'&&(m=path.match(/^\/shares\/([^/]+)$/))){const r=await projects.resolveShare(decodeURIComponent(m[1]));return r?json(200,r):err(404,'share_unavailable','Share link is unavailable or expired')}
    if(method==='DELETE'&&(m=path.match(/^\/shares\/([^/]+)$/))){const ok=await projects.revokeShare(decodeURIComponent(m[1]));return ok?json(204,null):err(404,'not_found','Share not found')}
    return err(404,'mock_route_not_found',`No mock route for ${method} ${path}`);
  }
  window.PRO4X4_MOCK_API={schemaVersion:'0.12.0',fetch:fetcher};
})();
