const contract=window.PRO4X4_QUOTE_CONTRACT;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:Number(n)%1?2:0}).format(Number(n)||0);const fmt=d=>d?new Date(d).toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'}):'—';
if(window.PRO4X4_AUTH?.current?.().role==='customer')window.PRO4X4_AUTH.setLocalRole('sales','PRO4X4 Sales');
const backend=window.PRO4X4_BACKEND?.active?.()||null;
async function readQuote(){const ref=new URLSearchParams(location.search).get('ref');if(ref&&backend){try{return await backend.getQuote(ref)}catch{}}const store=window.PRO4X4_SALES_STORE;if(ref){const hit=store?.get(ref);if(hit)return hit}return store?.getPreview?.()||null}
function lineTotal(a){return Object.values(a.pricing||{}).reduce((n,v)=>n+(v==null?0:Number(v)||0),0)}
async function render(){const host=$('#quoteDocument');host.innerHTML='<div class="quote-empty">Loading quote…</div>';const x=await readQuote();if(!x){host.innerHTML='<div class="quote-empty">No quote record found.</div>';return;}const q=x.quoteFinalisation||{},final=q.status==='finalised',w=x.weight||{};host.innerHTML=`<header class="quote-head"><div><div class="quote-logo">PRO<span>4X4</span></div><div class="quote-tag">BUILD YOUR ADVENTURE</div></div><div class="quote-id"><div class="quote-state ${final?'final':'draft'}">${final?'FORMAL QUOTE':'DRAFT PREVIEW'}</div><b>${esc(q.quoteNumber||x.reference)}</b><span>Build ref ${esc(x.reference)}</span><span>${x.project?.id?`Project ${esc(x.project.id)} · ${esc(x.project.revisionId||'')}`:''}</span></div></header>
<section class="quote-title"><div><div class="eyebrow">CUSTOM 4X4 BUILD PROPOSAL</div><h1>${esc(x.vehicle?.make)} ${esc(x.vehicle?.model)} <span>${esc(x.vehicle?.trim||'')}</span></h1><p>${esc(x.vehicle?.paint||'')} · ${esc(x.vehicle?.wheelTyre||'')}</p></div><div class="quote-dates"><span>Issued <b>${fmt(q.issuedAt)}</b></span><span>Valid until <b>${fmt(q.validUntil)}</b></span></div></section>
<section class="quote-customer"><div><span>CUSTOMER</span><b>${esc(x.lead?.name||'')}</b></div><div><span>CONTACT</span><b>${esc(x.lead?.phone||x.lead?.email||'')}</b><small>${esc(x.lead?.email||'')}</small></div><div><span>POSTCODE</span><b>${esc(x.lead?.postcode||'—')}</b></div><div><span>SALES OWNER</span><b>${esc(x.workflow?.owner||'PRO4X4')}</b></div></section>
<section class="quote-table-wrap"><table class="formal-table"><thead><tr><th>BUILD ITEM</th><th>SKU</th><th>STATUS</th><th class="right">PRICE</th></tr></thead><tbody>${(x.selections||[]).map(a=>`<tr><td><b>${esc(a.name)}</b><small>${esc(a.brand)}</small></td><td>${esc(a.sku)}</td><td>${esc(a.status)}</td><td class="right">${money(lineTotal(a))}</td></tr>`).join('')}</tbody></table></section>
<section class="quote-summary"><div class="quote-notes"><h3>Build notes</h3><p>${esc(x.lead?.notes||'No customer notes supplied.')}</p><h3>Weight planning</h3><p>Known accessory mass: <b>${w.knownAccessoryMassKg||0} kg</b>. ${w.unknownAccessoryMassCount||0} selected item(s) still have unverified mass.${w.remainingNominalPayloadKg!=null?` Planning payload remaining before occupants, cargo, towball download and unknown accessory mass: <b>${w.remainingNominalPayloadKg} kg</b>.`:''}</p><p class="quote-disclaimer">${esc(w.baseline?.note||'Weight figures are planning estimates only and do not replace weighbridge or engineering compliance checks.')}</p></div><div class="quote-total-card"><span>BUILD TOTAL</span><b>${money(x.pricing?.knownSubtotal)}</b><small>AUD · retail/GST treatment follows sourced catalogue pricing. Final tax invoice governs.</small></div></section>
<section class="quote-conditions"><h3>PRO4X4 quote conditions</h3><p>${final?'This proposal is based on the recorded catalogue revision and staff-approved fitment/pricing state at issue.':'This is a preview only and is not an offer to supply.'} Availability, freight, unforeseen fitment work, engineering requirements and customer-requested changes may alter the final invoice. Vehicle GVM, GCM, axle loads, towing limits and legal compliance remain subject to the exact completed vehicle and applicable approvals.</p></section><footer class="quote-footer"><b>PRO4X4</b><span>We Build Excitement · Build Your Adventure</span><span>${esc(x.catalogue?.revision||'base catalogue')} · ${x.project?.revisionId?`project ${esc(x.project.revisionId)} · `:''}contract ${esc(x.contract?.version||x.schemaVersion||'')}</span></footer>`}
render();
