import {resultURL} from '../support/results.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {GovernanceRegistry,candidateIdentity,binaryHash,hash} from '../../subsystems/governance/registry.mjs';
import {DatabaseSync} from 'node:sqlite';
import {publicProjection} from '../../subsystems/governance/projection.mjs';
import {governancePolicy} from '../../subsystems/visual-eligibility/governance-policy.mjs';
import {eligibility} from '../../subsystems/visual-eligibility/adapter.mjs';
import {sourceArchive} from '../../tools/source-archive.mjs';
import referenceGate from '../../subsystems/governance/vendor/canonical-review-gate.js';
const root=new URL('../../',import.meta.url),json=p=>JSON.parse(fs.readFileSync(new URL(p,root))),baseline=json('subsystems/governance/baseline.json');
const archives={wf3:sourceArchive('wf3'),wf4:sourceArchive('wf4'),wf5:sourceArchive('wf5')};
const results=[];function test(name,fn){fn();results.push({name,status:'PASS'});console.log('PASS '+name);}
const rejected=(fn,code)=>assert.throws(fn,e=>e.code===code,code);
const actors={curator:['curator'],reference:['reference-reviewer'],processor:['processor'],reviewer:['reviewer'],rights:['rights-reviewer'],seal:['sealer'],publish:['publisher']};
function setup(){
  const blobs=new Map(),source=(name,bytes=name)=>{const b=Buffer.from(bytes);blobs.set(name,b);return {source:{path:name},sha256:binaryHash(b)};};
  const g=new GovernanceRegistry({baseline:{referenceRecords:[],masterRecords:[],candidates:[],variant:'test'},actors,readBinary:s=>blobs.get(s.path)});
  g.registerReference({id:'ref',vehicleId:'qa',variant:'qa-only',rights:'synthetic-test-reference',...source('ref')},'curator');g.approveReference('ref',binaryHash(blobs.get('ref')),'reference');
  g.registerMaster({id:'master',vehicleId:'qa',variant:'qa-only',viewId:'front34',referenceIds:['ref'],requiredChecks:['identity','edge-quality','no-invented-accessories']},'curator');
  g.acceptMasterContract('master',{masterId:'master',viewId:'front34',...source('contract')},'reference');
  const input={vehicleId:'qa',variant:'qa-only',viewId:'front34',candidateId:'C01-v1',masterId:'master',referenceIds:['ref'],layerId:'base',exactSku:null,renderState:{paint:'black'},...source('candidate')};
  const c=g.stageCandidate(input,'processor');
  const ev={candidateId:c.id,sha256:c.sha256,viewId:c.viewId,source:source('evidence').source,evidenceSha256:binaryHash(blobs.get('evidence')),cameraMatched:true,reconstruction:'pass',checks:{identity:'pass','edge-quality':'pass','no-invented-accessories':'pass'}};
  const right={candidateId:c.id,sha256:c.sha256,scope:'production-binary',source:source('rights').source,evidenceSha256:binaryHash(blobs.get('rights'))};
  const ready=()=>{g.recordEvidence(c.id,ev,'processor');g.recordBinaryRights(c.id,right,'rights');};
  const approve=()=>{ready();const claim=g.claim(c.id,'reviewer');const d=g.decide(c.id,claim.checksum,'approved','reviewer');const seal=g.seal(c.id,d.checksum,'seal');return g.promote(c.id,seal.checksum,'publish');};
  return {g,blobs,source,input,c,ev,right,ready,approve};
}
function fixtureTest(name,fn){test(name,()=>{const f=setup();try{fn(f);}finally{f.g.close();}});}
const actual=new GovernanceRegistry({baseline,readBinary:s=>archives[s.branch]?.get(s.path)});
try{
test('WF5-OWNER-REFERENCE-PACK-INTEGRITY and all WF3 source hashes',()=>{for(const s of baseline.sourceFiles)assert.equal(binaryHash(archives[s.branch].get(s.path)),s.sha256,s.path);for(const r of baseline.referenceRecords)assert.equal(binaryHash(archives.wf3.get('wf3_run56/'+r.source)),r.file.checksumSha256);});
test('Exact WF4 validator source bytes retained',()=>{for(const v of json('subsystems/governance/vendor-hashes.json'))assert.equal(binaryHash(fs.readFileSync(new URL('subsystems/governance/vendor/'+v.path,root))),v.sha256);});
test('WF4 approved reference decisions remain current; three masters retained',()=>{for(const m of baseline.masterRecords)assert.deepEqual(referenceGate.referenceProblems(m,baseline.referenceRecords),[]);assert.deepEqual(actual.counts(),{references:9,approvedReferences:9,masters:3,candidates:9,claims:0,decisions:0,seals:0,production:0});});
test('Nine unique vehicle variant view version identities; no generic Candidate 05',()=>{assert.equal(new Set(baseline.candidates.map(c=>c.id)).size,9);for(const c of baseline.candidates)assert.equal(c.id,candidateIdentity(c));rejected(()=>candidateIdentity({candidateId:'Candidate 05'}),'candidate_identity_incomplete');});
test('R34 Candidate 05 exact binary mask provenance and unresolved evidence retained',()=>{const c=baseline.candidates.find(c=>c.candidateId==='Y62-R34-V1-CANDIDATE-05'),r=c.evidence.manifest;assert.equal(c.state,'master-draft');assert.equal(c.cameraMatched,false);assert.equal(c.productionEligible,false);assert.equal(r.review.cleanNeutralReconstruction,'fail');assert.equal(r.review.productionBinaryRights,'hold');assert.equal(r.source.rights,'owner-project-approved');assert.equal(c.binaryRights,null);for(const k of ['source','candidate','mask','preview','board'])assert.equal(binaryHash(archives.wf3.get('wf3_run56/'+r[k].file)),r[k].sha256);assert(c.blockers.includes('F34-first'));});
test('WF4 registry decisions not overwritten by newer R34 evidence',()=>{const r=baseline.reconciliation;assert.equal(r.f34State,'blocked-upstream');assert.equal(r.f34RegistryCandidate,'Y62-F34-V1-CANDIDATE-02');assert.equal(r.sideSourceGap,'open/current');assert.equal(r.sideCamera,'calibration');assert.equal(r.r34RegistryState,'awaiting-wf3-candidate');assert.equal(r.f34Candidate05BinaryPresent,false);});
test('Safe policy has no registry/reviewer/candidate binaries and no Y62 production',()=>{const p=publicProjection(actual,baseline,json('consolidation/manifest.json').activeApplication.requiredAssets);assert.deepEqual(p,governancePolicy);assert.equal(p.ranger.state,'preview');assert.equal(p.ranger.assets.length,10);assert.equal(p.y62.productionCount,0);assert.equal(p.y62.baseState,'unavailable');assert(!/OWNER-Y62|reviewer|referenceRecords|\.png|candidateId/.test(JSON.stringify(p)));});
test('WF5-CUSTOMER-DRAFT-ISOLATION: blocked Y62 has no 3D fallback',()=>{const r=eligibility({decision:{vehicleId:'nissan-y62-warrior-2025'},mapping:json('subsystems/catalogue/alpha93-mapping.json')});assert.equal(r.baseState,'unavailable');assert.equal(r.productionApproved,false);assert(Object.values(r.layers).every(l=>!l.visible));assert.equal(r.fallback,'none');});
}finally{actual.close();}
fixtureTest('WF4-DIRECT-PRODUCTION-REVIEW/EVIDENCE: direct production rejected',({g,c})=>{rejected(()=>g.promote(c.id,'fabricated','publish'),'candidate_evidence_required');rejected(()=>g.promote('Candidate 05','fabricated','publish'),'unknown_candidates');});
fixtureTest('WF4-MASTER-REFERENCE-ID-VALIDITY: invalid reference rejected',({g,input,source})=>rejected(()=>g.stageCandidate({...input,candidateId:'bad',referenceIds:['missing'],...source('new')},'processor'),'master_reference_candidate_mismatch'));
fixtureTest('WF4-MASTER-REFERENCE-BACKING: nonexistent master rejected',({g,input})=>rejected(()=>g.stageCandidate({...input,candidateId:'bad',masterId:'missing'},'processor'),'unknown_masters'));
fixtureTest('WF4-MASTER-BRIEF-REFERENCE-BINDING: unrelated valid reference rejected',({g,input,source})=>{g.registerReference({id:'other',vehicleId:'qa',variant:'qa-only',rights:'QA',...source('other')},'curator');g.approveReference('other',binaryHash(Buffer.from('other')),'reference');rejected(()=>g.stageCandidate({...input,candidateId:'bad',referenceIds:['other']},'processor'),'master_reference_candidate_mismatch');});
fixtureTest('Wrong vehicle/view/variant candidate binding rejected',({g,input})=>{for(const field of ['vehicleId','viewId','variant'])rejected(()=>g.stageCandidate({...input,[field]:'wrong'},'processor'),'master_reference_candidate_mismatch');});
fixtureTest('WF4-REVIEWER-IDENTITY-AUTHENTICITY: unauthorized reviewer rejected',({g,c,ready})=>{ready();rejected(()=>g.claim(c.id,'customer'),'unauthorized_governance_actor');rejected(()=>g.claim(c.id,{actorId:'reviewer',role:'admin'}),'unauthorized_governance_actor');});
fixtureTest('Missing production binary rights cannot promote',({g,c,ev})=>{g.recordEvidence(c.id,ev,'processor');rejected(()=>g.claim(c.id,'reviewer'),'production_binary_rights_missing');});
fixtureTest('Camera mismatch cannot promote',({g,c,ev,right})=>{g.recordEvidence(c.id,{...ev,cameraMatched:false},'processor');g.recordBinaryRights(c.id,right,'rights');rejected(()=>g.claim(c.id,'reviewer'),'camera_mismatch');});
fixtureTest('Clean-neutral reconstruction failure cannot promote',({g,c,ev,right})=>{g.recordEvidence(c.id,{...ev,reconstruction:'fail'},'processor');g.recordBinaryRights(c.id,right,'rights');rejected(()=>g.claim(c.id,'reviewer'),'reconstruction_failed');});
fixtureTest('Required WF4 review check failure cannot promote',({g,c,ev,right})=>{g.recordEvidence(c.id,{...ev,checks:{identity:'pass'}},'processor');g.recordBinaryRights(c.id,right,'rights');rejected(()=>g.claim(c.id,'reviewer'),'required_review_checks_failed');});
fixtureTest('Candidate binary changed after evidence rejected',({g,c,ready,blobs})=>{ready();blobs.set('candidate',Buffer.from('tampered'));rejected(()=>g.claim(c.id,'reviewer'),'binary_evidence_mismatch');});
fixtureTest('Source evidence bytes changed after claim rejected',({g,c,ready,blobs})=>{ready();const claim=g.claim(c.id,'reviewer');blobs.set('evidence',Buffer.from('changed'));rejected(()=>g.decide(c.id,claim.checksum,'approved','reviewer'),'binary_evidence_mismatch');});
fixtureTest('Changed camera contract invalidates production eligibility',({g,c,approve,blobs})=>{approve();blobs.set('contract',Buffer.from('changed-camera'));assert.equal(g.resolve(c).state,'unavailable');assert.equal(g.counts().production,0);});
fixtureTest('Candidate bytes changed after production have no customer fallback',({g,c,approve,blobs})=>{approve();blobs.set('candidate',Buffer.from('changed-binary'));assert.equal(g.resolve(c).state,'unavailable');assert.equal(g.resolve(c).binary,null);});
fixtureTest('Stale claim after source reference change rejected',({g,c,ready,source})=>{ready();const claim=g.claim(c.id,'reviewer');g.replaceReference('ref',{expectedSha:binaryHash(Buffer.from('ref')),rights:'QA renewed',...source('ref-new')},'curator');g.approveReference('ref',binaryHash(Buffer.from('ref-new')),'reference');rejected(()=>g.decide(c.id,claim.checksum,'approved','reviewer'),'stale_or_unauthorized_claim');});
fixtureTest('Evidence refresh invalidates existing claim/decision',({g,c,ev,ready})=>{ready();const claim=g.claim(c.id,'reviewer');g.recordEvidence(c.id,ev,'processor');rejected(()=>g.decide(c.id,claim.checksum,'approved','reviewer'),'stale_or_unauthorized_claim');});
fixtureTest('WF4-CANDIDATE-EVIDENCE-RESET on identity/binary replacement',({g,c,input,source,approve})=>{approve();const next=g.stageCandidate({...input,candidateId:'C01-v2',...source('new-bytes'),evidence:{approved:true},binaryRights:{approved:true},seal:'old'},'processor');assert.equal(next.evidence,null);assert.equal(next.binaryRights,null);assert.equal(next.cameraMatched,false);assert.equal(next.productionEligible,false);assert.equal(next.state,'master-draft');assert.equal(g.resolve(c).state,'approved');});
fixtureTest('WF4-PRODUCTION-BINARY/IDENTITY-IMMUTABILITY',({g,c,input,ev,approve})=>{approve();rejected(()=>g.stageCandidate({...input,sha256:'0'.repeat(64)},'processor'),'candidate_version_immutable');rejected(()=>g.recordEvidence(c.id,ev,'processor'),'production_version_immutable');const snap=g.snapshot();snap.candidates[0].viewId='rear34';assert.equal(g.resolve(c).state,'approved');});
fixtureTest('WF4-PRODUCTION-TUPLE-UNIQUENESS rejects second approved tuple',({g,c,input,source,ev,right,approve})=>{approve();const n=g.stageCandidate({...input,candidateId:'duplicate-v1',...source('dup')},'processor');g.recordEvidence(n.id,{...ev,candidateId:n.id,sha256:n.sha256},'processor');g.recordBinaryRights(n.id,{...right,candidateId:n.id,sha256:n.sha256},'rights');const cl=g.claim(n.id,'reviewer'),d=g.decide(n.id,cl.checksum,'approved','reviewer'),s=g.seal(n.id,d.checksum,'seal');rejected(()=>g.promote(n.id,s.checksum,'publish'),'duplicate_production_tuple');assert.equal(g.resolve(c).state,'approved');});
fixtureTest('WF4-BLOCKED-FITMENT-PRECEDENCE overrides approved visual',({g,c,approve})=>{approve();g.block(c,'curator');assert.deepEqual(g.resolve(c),{state:'blocked',productionApproved:false,binary:null,fallback:'none'});});
fixtureTest('WF4-RENDER-STATE-EXACTNESS and exact SKU no fallback',({g,c,approve})=>{approve();for(const q of [{...c,renderState:undefined},{...c,renderState:{paint:'white'}},{...c,exactSku:'unknown'},{...c,variant:'different'}]){const r=g.resolve(q);assert.equal(r.state,'unavailable');assert.equal(r.binary,null);assert.equal(r.fallback,'none');}});
fixtureTest('Full reference-master-candidate-claim-decision-seal-production positive control',({g,c,approve})=>{approve();assert.equal(g.resolve(c).state,'approved');assert.deepEqual(g.counts(),{references:1,approvedReferences:1,masters:1,candidates:1,claims:1,decisions:1,seals:1,production:1});});
fixtureTest('Claim retry idempotent and stale/foreign claim rejected',({g,c,ready})=>{ready();const cl=g.claim(c.id,'reviewer');assert.deepEqual(g.claim(c.id,'reviewer'),cl);rejected(()=>g.decide(c.id,'wrong','approved','reviewer'),'stale_or_unauthorized_claim');rejected(()=>g.decide(c.id,cl.checksum,'approved','processor'),'unauthorized_governance_actor');});
fixtureTest('Production seal cannot bypass reviewer decision or be forged',({g,c,ready})=>{ready();rejected(()=>g.seal(c.id,'invented','seal'),'current_approved_decision_required');rejected(()=>g.promote(c.id,'invented','publish'),'current_production_seal_required');});
fixtureTest('F34-first enforced for complete R34 synthetic evidence',({g,source,ev,right})=>{g.registerMaster({id:'rear-master',vehicleId:'qa',variant:'qa-only',viewId:'rear34',referenceIds:['ref'],requiredChecks:['identity']},'curator');g.acceptMasterContract('rear-master',{masterId:'rear-master',viewId:'rear34',...source('rear-contract')},'reference');const c=g.stageCandidate({vehicleId:'qa',variant:'qa-only',viewId:'rear34',candidateId:'R05',masterId:'rear-master',referenceIds:['ref'],layerId:'base',exactSku:null,renderState:{paint:'black'},...source('rear')},'processor');g.recordEvidence(c.id,{...ev,candidateId:c.id,sha256:c.sha256,viewId:'rear34'},'processor');g.recordBinaryRights(c.id,{...right,candidateId:c.id,sha256:c.sha256},'rights');rejected(()=>g.claim(c.id,'reviewer'),'F34_first');});
test('Durable governance ledger reload, tamper rejection and no customer grants',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'alpha94-governance-')),filename=path.join(dir,'test.sqlite'),empty={referenceRecords:[],masterRecords:[],candidates:[],variant:'qa'};
  try{let g=new GovernanceRegistry({baseline:empty,filename,actors,readBinary:()=>Buffer.from('ref')});g.registerReference({id:'ref',vehicleId:'qa',variant:'qa',rights:'QA',source:{path:'ref'},sha256:binaryHash(Buffer.from('ref'))},'curator');const before=g.snapshot();g.close();g=new GovernanceRegistry({baseline:empty,filename});assert.deepEqual(g.snapshot(),before);rejected(()=>g.approveReference('ref',before.references[0].sha256,'curator'),'unauthorized_governance_actor');g.close();
    const db=new DatabaseSync(filename);assert.throws(()=>db.exec("UPDATE governance_events SET sha='tamper'"),/immutable governance event/);assert.throws(()=>db.exec('DELETE FROM governance_events'),/immutable governance event/);db.exec('DROP TRIGGER governance_no_update');db.exec("UPDATE governance_events SET sha='tamper'");db.close();rejected(()=>new GovernanceRegistry({baseline:empty,filename}),'governance_audit_invalid');
  }finally{assert(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep+'alpha94-governance-'));fs.rmSync(dir,{recursive:true});}
});
console.log(JSON.stringify({suite:'Stage7 current Alpha94 governance',tests:results.length,status:'PASS',sourceProductionVisuals:0}));
fs.writeFileSync(resultURL('governance.json'),JSON.stringify({status:'PASS',tests:results.length,results},null,2)+'\n');
