'use strict';
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const hmac=(key,data,encoding)=>crypto.createHmac('sha256',key).update(data).digest(encoding);
const awsEncode=s=>encodeURIComponent(String(s)).replace(/[!'()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase());
const canonicalPath=pathname=>pathname.split('/').map((seg,i)=>i===0?'':awsEncode(decodeURIComponent(seg||''))).join('/');
const canonicalQuery=params=>[...params.entries()].map(([k,v])=>[awsEncode(k),awsEncode(v)]).sort((a,b)=>a[0]===b[0]?a[1].localeCompare(b[1]):a[0].localeCompare(b[0])).map(([k,v])=>`${k}=${v}`).join('&');
const amzDate=d=>d.toISOString().replace(/[:-]|\.\d{3}/g,'');
const dateStamp=d=>amzDate(d).slice(0,8);
function xmlDecode(s=''){return String(s).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&')}
function parseListObjects(xml=''){const out=[];const re=/<Contents>([\s\S]*?)<\/Contents>/g;let m;while((m=re.exec(String(xml)))){const block=m[1],pick=t=>{const x=block.match(new RegExp(`<${t}>([\\s\\S]*?)<\\/${t}>`));return x?xmlDecode(x[1]):null};out.push({objectKey:pick('Key'),sizeBytes:Number(pick('Size')||0),mtime:pick('LastModified')||null})}const trunc=/<IsTruncated>true<\/IsTruncated>/.test(String(xml)),token=String(xml).match(/<NextContinuationToken>([\s\S]*?)<\/NextContinuationToken>/)?.[1]||null;return {objects:out.filter(x=>x.objectKey),isTruncated:trunc,nextContinuationToken:token?xmlDecode(token):null}}
class LocalAssetStore{
  constructor(root){this.root=path.resolve(root);this.mode='local';this.cdnBaseUrl=null;fs.mkdirSync(this.root,{recursive:true,mode:0o750})}
  async put(objectKey,buf){const full=path.join(this.root,...String(objectKey).split('/'));fs.mkdirSync(path.dirname(full),{recursive:true,mode:0o750});if(!fs.existsSync(full)){const tmp=full+'.tmp-'+process.pid;fs.writeFileSync(tmp,buf,{mode:0o640});fs.renameSync(tmp,full)}return {objectKey}}
  resolve(objectKey){const full=path.resolve(this.root,...String(objectKey).split('/'));if(!full.startsWith(this.root+path.sep))return null;return fs.existsSync(full)?full:null}
  async read(objectKey){const f=this.resolve(objectKey);return f?fs.readFileSync(f):null}
  async inventory(){const base=path.join(this.root,'sha256'),out=[];if(!fs.existsSync(base))return out;const walk=d=>{for(const ent of fs.readdirSync(d,{withFileTypes:true})){const full=path.join(d,ent.name);if(ent.isDirectory())walk(full);else if(ent.isFile()){const rel=path.relative(this.root,full).split(path.sep).join('/'),stat=fs.statSync(full);out.push({objectKey:rel,sizeBytes:stat.size,mtime:stat.mtime.toISOString()})}}};walk(base);return out.sort((a,b)=>a.objectKey.localeCompare(b.objectKey))}
  async remove(objectKey){const f=this.resolve(objectKey);if(!f)return false;fs.unlinkSync(f);let d=path.dirname(f);while(d.startsWith(this.root+path.sep)&&d!==this.root){try{fs.rmdirSync(d)}catch{break}d=path.dirname(d)}return true}
  publicUrl(){return null} presignGet(){return null}
}
class S3CompatibleAssetStore{
  constructor({endpoint,bucket,region='us-east-1',accessKeyId,secretAccessKey,sessionToken='',forcePathStyle=true,cdnBaseUrl='',fetcher=globalThis.fetch}={}){if(typeof fetcher!=='function')throw new Error('S3-compatible storage requires fetch support');this.endpoint=new URL(endpoint);this.bucket=bucket;this.region=region;this.accessKeyId=accessKeyId;this.secretAccessKey=secretAccessKey;this.sessionToken=sessionToken||'';this.forcePathStyle=!!forcePathStyle;this.cdnBaseUrl=cdnBaseUrl?String(cdnBaseUrl).replace(/\/+$/,''):null;this.fetcher=fetcher;this.mode='s3'}
  objectUrl(objectKey='',query=null){const key=String(objectKey).split('/').filter(Boolean).map(awsEncode).join('/'),u=new URL(this.endpoint.toString());let base=u.pathname.replace(/\/+$/,'');if(this.forcePathStyle){u.pathname=`${base}/${awsEncode(this.bucket)}${key?`/${key}`:''}`.replace(/\/+/g,'/')}else{u.hostname=`${this.bucket}.${u.hostname}`;u.pathname=`${base}${key?`/${key}`:''}`.replace(/\/+/g,'/')||'/'}u.search='';if(query)for(const [k,v] of Object.entries(query))if(v!=null)u.searchParams.set(k,String(v));return u}
  signingKey(stamp){const kDate=hmac(Buffer.from('AWS4'+this.secretAccessKey),stamp),kRegion=hmac(kDate,this.region),kService=hmac(kRegion,'s3');return hmac(kService,'aws4_request')}
  signedHeaders(method,u,{payloadHash=hash(Buffer.alloc(0)),now=new Date(),headers={}}={}){const stamp=dateStamp(now),timestamp=amzDate(now),all={'host':u.host,'x-amz-content-sha256':payloadHash,'x-amz-date':timestamp,...Object.fromEntries(Object.entries(headers).map(([k,v])=>[String(k).toLowerCase(),String(v).trim()]))};if(this.sessionToken)all['x-amz-security-token']=this.sessionToken;const names=Object.keys(all).sort(),canonicalHeaders=names.map(n=>`${n}:${all[n]}\n`).join(''),signedNames=names.join(';'),scope=`${stamp}/${this.region}/s3/aws4_request`,query=canonicalQuery(u.searchParams),request=[method.toUpperCase(),canonicalPath(u.pathname)||'/',query,canonicalHeaders,signedNames,payloadHash].join('\n'),stringToSign=['AWS4-HMAC-SHA256',timestamp,scope,hash(request)].join('\n'),signature=hmac(this.signingKey(stamp),stringToSign,'hex');return {...all,authorization:`AWS4-HMAC-SHA256 Credential=${this.accessKeyId}/${scope}, SignedHeaders=${signedNames}, Signature=${signature}`}}
  presignGet(objectKey,expiresSeconds=300,{now=new Date()}={}){const expires=Math.max(1,Math.min(604800,Number(expiresSeconds)||300)),u=this.objectUrl(objectKey),stamp=dateStamp(now),timestamp=amzDate(now),scope=`${stamp}/${this.region}/s3/aws4_request`;u.searchParams.set('X-Amz-Algorithm','AWS4-HMAC-SHA256');u.searchParams.set('X-Amz-Credential',`${this.accessKeyId}/${scope}`);u.searchParams.set('X-Amz-Date',timestamp);u.searchParams.set('X-Amz-Expires',String(expires));u.searchParams.set('X-Amz-SignedHeaders','host');if(this.sessionToken)u.searchParams.set('X-Amz-Security-Token',this.sessionToken);const canonical=['GET',canonicalPath(u.pathname)||'/',canonicalQuery(u.searchParams),`host:${u.host}\n`,'host','UNSIGNED-PAYLOAD'].join('\n'),stringToSign=['AWS4-HMAC-SHA256',timestamp,scope,hash(canonical)].join('\n'),signature=hmac(this.signingKey(stamp),stringToSign,'hex');u.searchParams.set('X-Amz-Signature',signature);return u.toString()}
  async request(method,u,{body=null,mimeType='application/octet-stream'}={}){const payload=body==null?Buffer.alloc(0):Buffer.from(body),headers=this.signedHeaders(method,u,{payloadHash:hash(payload)});if(body!=null)headers['content-type']=mimeType;const r=await this.fetcher(u,{method,headers,body:body==null?undefined:payload,redirect:'follow'});if(!r.ok){const text=await r.text().catch(()=> '');throw Object.assign(new Error(`S3-compatible storage ${method} failed (${r.status})${text?`: ${text.slice(0,300)}`:''}`),{status:502,code:'asset_storage_error',providerStatus:r.status})}return r}
  async put(objectKey,buf,{mimeType='application/octet-stream'}={}){await this.request('PUT',this.objectUrl(objectKey),{body:buf,mimeType});return {objectKey}}
  async read(objectKey){const r=await this.request('GET',this.objectUrl(objectKey));return Buffer.from(await r.arrayBuffer())}
  async inventory(){let token=null,out=[];do{const u=this.objectUrl('',{'list-type':'2','prefix':'sha256/'});if(token)u.searchParams.set('continuation-token',token);const page=parseListObjects(await (await this.request('GET',u)).text());out.push(...page.objects);token=page.isTruncated?page.nextContinuationToken:null}while(token);return out.sort((a,b)=>a.objectKey.localeCompare(b.objectKey))}
  async remove(objectKey){const r=await this.request('DELETE',this.objectUrl(objectKey));return r.ok}
  publicUrl(objectKey){return this.cdnBaseUrl?`${this.cdnBaseUrl}/${String(objectKey).split('/').map(awsEncode).join('/')}`:null}
}
module.exports={LocalAssetStore,S3CompatibleAssetStore,parseListObjects,awsEncode,canonicalQuery,canonicalPath,hash};
