'use strict';
const crypto=require('node:crypto');
const zlib=require('node:zlib');
const {LocalAssetStore,S3CompatibleAssetStore}=require('./asset-storage');
function sha256(buf){return crypto.createHash('sha256').update(buf).digest('hex')}
function pngInfo(buf){const sig=Buffer.from('89504e470d0a1a0a','hex');if(buf.length<33||!buf.subarray(0,8).equals(sig))return null;const width=buf.readUInt32BE(16),height=buf.readUInt32BE(20),bitDepth=buf[24],colorType=buf[25],interlace=buf[28];let off=8,idat=[];while(off+12<=buf.length){const len=buf.readUInt32BE(off),type=buf.toString('ascii',off+4,off+8);if(type==='IDAT')idat.push(buf.subarray(off+8,off+8+len));off+=12+len;if(type==='IEND')break}let hasAlpha=null,verified=false;if(bitDepth===8&&interlace===0&&(colorType===6||colorType===4)&&idat.length){try{const raw=zlib.inflateSync(Buffer.concat(idat)),channels=colorType===6?4:2,bpp=channels,stride=width*channels;let prev=Buffer.alloc(stride),pos=0;hasAlpha=false;for(let y=0;y<height;y++){const filter=raw[pos++],scan=Buffer.from(raw.subarray(pos,pos+stride));pos+=stride;for(let x=0;x<stride;x++){const a=x>=bpp?scan[x-bpp]:0,b=prev[x]||0,c=x>=bpp?(prev[x-bpp]||0):0;if(filter===1)scan[x]=(scan[x]+a)&255;else if(filter===2)scan[x]=(scan[x]+b)&255;else if(filter===3)scan[x]=(scan[x]+Math.floor((a+b)/2))&255;else if(filter===4){const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c),pr=pa<=pb&&pa<=pc?a:pb<=pc?b:c;scan[x]=(scan[x]+pr)&255}}for(let x=channels-1;x<stride;x+=channels)if(scan[x]<255){hasAlpha=true;break}prev=scan;if(hasAlpha)break}verified=true}catch{hasAlpha=null;verified=false}}return {mimeType:'image/png',ext:'.png',width,height,alphaCapable:colorType===4||colorType===6,hasAlpha,transparencyVerified:verified}}
function webpInfo(buf){if(buf.length<30||buf.toString('ascii',0,4)!=='RIFF'||buf.toString('ascii',8,12)!=='WEBP')return null;const chunk=buf.toString('ascii',12,16);let width=null,height=null,alphaCapable=false;if(chunk==='VP8X'){alphaCapable=!!(buf[20]&0x10);width=1+buf[24]+(buf[25]<<8)+(buf[26]<<16);height=1+buf[27]+(buf[28]<<8)+(buf[29]<<16)}return {mimeType:'image/webp',ext:'.webp',width,height,alphaCapable,hasAlpha:null,transparencyVerified:false}}
function inspect(buf){const info=pngInfo(buf)||webpInfo(buf);if(!info)throw Object.assign(new Error('Unsupported asset binary. Use PNG or WebP.'),{status:415,code:'unsupported_asset_type'});if(!info.width||!info.height)throw Object.assign(new Error('Asset dimensions could not be verified server-side'),{status:422,code:'asset_inspection_failed'});return {...info,checksumSha256:sha256(buf),sizeBytes:buf.length}}
class AssetVault{
  constructor(configOrRoot){const c=typeof configOrRoot==='string'?{assetStorageDriver:'local',assetVaultDir:configOrRoot}:configOrRoot||{};this.mode=c.assetStorageDriver||'local';this.store=this.mode==='s3'?new S3CompatibleAssetStore({endpoint:c.assetS3Endpoint,bucket:c.assetS3Bucket,region:c.assetS3Region,accessKeyId:c.assetS3AccessKeyId,secretAccessKey:c.assetS3SecretAccessKey,sessionToken:c.assetS3SessionToken,forcePathStyle:c.assetS3ForcePathStyle,cdnBaseUrl:c.assetCdnBaseUrl,fetcher:c.assetStorageFetcher}):new LocalAssetStore(c.assetVaultDir);this.cdnBaseUrl=c.assetCdnBaseUrl||null}
  async put(assetId,buf){const meta=inspect(buf),rel=`sha256/${meta.checksumSha256.slice(0,2)}/${meta.checksumSha256}${meta.ext}`;await this.store.put(rel,buf,{mimeType:meta.mimeType,checksumSha256:meta.checksumSha256});return {...meta,objectKey:rel,storedAt:new Date().toISOString(),assetId,storageDriver:this.mode}}
  resolve(objectKey){return typeof this.store.resolve==='function'?this.store.resolve(objectKey):null}
  async read(objectKey){try{return await this.store.read(objectKey)}catch(e){if(e?.providerStatus===404)return null;throw e}}
  async inventory(){return this.store.inventory()}
  async verify(objectKey,expectedChecksum=null){const buf=await this.read(objectKey);if(!buf)return {objectKey,exists:false,checksumSha256:null,checksumMatches:false,sizeBytes:0};const checksumSha256=sha256(buf);return {objectKey,exists:true,checksumSha256,checksumMatches:expectedChecksum?checksumSha256===expectedChecksum:true,sizeBytes:buf.length}}
  async remove(objectKey){try{return await this.store.remove(objectKey)}catch(e){if(e?.providerStatus===404)return false;throw e}}
  publicUrl(objectKey){return typeof this.store.publicUrl==='function'?this.store.publicUrl(objectKey):null}
  presignGet(objectKey,expiresSeconds){return typeof this.store.presignGet==='function'?this.store.presignGet(objectKey,expiresSeconds):null}
  status(){return {driver:this.mode,cdnEnabled:!!this.cdnBaseUrl,localRoot:this.mode==='local'?this.store.root:null,s3Bucket:this.mode==='s3'?this.store.bucket:null,s3Region:this.mode==='s3'?this.store.region:null}}
}
module.exports={AssetVault,inspect,pngInfo,webpInfo,sha256};
