(function(){
  const P=window.PRO4X4_PERSISTENCE;
  function localReadiness(vehicleId=window.Y62_READINESS_PLAN?.vehicleId){const plan=window.Y62_READINESS_PLAN,assets=window.PRO4X4_ASSET_REGISTRY?.load?.()||[];if(!plan||vehicleId!==plan.vehicleId)throw Object.assign(new Error('Render readiness plan not found'),{status:404});const rank={'production-ready':0,'candidate':1,'asset-needed':2,'reference-only':3,'blocked-fitment':4,'retired':5},cells=plan.expectedSlots().map(slot=>{const matches=assets.filter(a=>a.viewId===slot.viewId&&a.layerId===slot.layerId&&(a.exactSku||null)===(slot.exactSku||null)&&Object.entries(slot.renderState||{}).every(([k,v])=>a.renderState?.[k]===v)),asset=[...matches].sort((a,b)=>(rank[a.status]??99)-(rank[b.status]??99))[0]||null;return {...slot,registered:!!asset,assetId:asset?.assetId||null,status:asset?.status||'slot-missing',productionReady:asset?.status==='production-ready',nextAction:!asset?'create-slot':asset.status==='production-ready'?'ready':asset.status==='candidate'?'review-candidate':asset.status==='blocked-fitment'?'resolve-fitment':asset.status==='reference-only'?'source-genuine-layer':'source-asset'}}),views=plan.views.map(v=>{const x=cells.filter(c=>c.viewId===v.id);return {viewId:v.id,label:v.label,cameraProfileId:v.cameraProfileId,cameraState:v.cameraState,planned:x.length,registered:x.filter(c=>c.registered).length,productionReady:x.filter(c=>c.productionReady).length,missingSlots:x.filter(c=>!c.registered).length,cells:x}}),front=cells.filter(c=>c.viewId==='front34'),ready=cells.filter(c=>c.productionReady).length,registered=cells.filter(c=>c.registered).length;let health='red',healthReason='Front 3/4 validated core state coverage is incomplete.';if(front.length&&front.every(c=>c.productionReady)){health=ready===cells.length?'green':'amber';healthReason=health==='green'?'All validated core render-state slots are production-ready.':'Front 3/4 core states are ready; broader view/state coverage remains incomplete.'}return {schemaVersion:'0.23.0',vehicleId,generatedAt:new Date().toISOString(),policy:'exact-state-no-substitution',summary:{plannedSlots:cells.length,registeredSlots:registered,missingSlots:cells.length-registered,productionReadySlots:ready,coveragePct:cells.length?Math.round(ready/cells.length*100):0,front34ProductionReady:front.filter(c=>c.productionReady).length,front34Planned:front.length,health,healthReason},telemetry:{windowHours:24,eventCount:0,loadSuccess:0,loadErrors:0,retries:0,loadSuccessRate:null,retryRate:null,thresholds:plan.thresholds,mode:'browser-local'},views}}
  function localSyncReadiness(vehicleId=window.Y62_READINESS_PLAN?.vehicleId){const plan=window.Y62_READINESS_PLAN,before=localReadiness(vehicleId),created=[];for(const view of before.views)for(const slot of view.cells){if(slot.registered)continue;const asset={schemaVersion:'0.23.0',assetId:slot.assetIdHint,vehicleId:slot.vehicleId,viewId:slot.viewId,layerId:slot.layerId,exactSku:slot.exactSku,status:'asset-needed',source:null,renderState:{...slot.renderState},provenance:{sourceType:'unknown',sourceUrl:null,licenceStatus:'unknown',licenceNote:'Explicit validated render-state slot. Genuine source and usage rights are required before candidate promotion.',capturedAt:null},file:{checksumSha256:null,mimeType:null,width:null,height:null,hasAlpha:null},cameraGeometry:{profileId:slot.cameraProfileId,matched:false,notes:slot.cameraState==='locked'?'Must be matched to the locked camera profile before production approval.':'View camera profile remains calibration-only; asset can be sourced but cannot be production-approved yet.'},fitmentScope:[slot.vehicleId,slot.exactSku||'vehicle-state',slot.stateKey],approval:{state:'not-reviewed',approvedBy:null,approvedAt:null,notes:`Readiness slot created for ${slot.label}. No visual binary is implied.`},history:[{at:new Date().toISOString(),action:'readiness.slot.created',note:`Explicit asset-needed slot created for ${slot.stateKey}; no stand-in artwork attached.`}]};window.PRO4X4_ASSET_REGISTRY.upsert(asset);created.push(asset.assetId)}return {schemaVersion:'0.23.0',vehicleId,createdCount:created.length,existingCount:before.summary.registeredSlots,created,readiness:localReadiness(vehicleId)}}
  const local={
    mode:'local-adapter',
    async health(){return {ok:true,schemaVersion:'0.12.0',service:'browser-local',authMode:'browser-local'}},
    async getSession(){const a=window.PRO4X4_AUTH.current();return {schemaVersion:'0.12.0',authenticated:true,source:'browser-local',actor:a,capabilities:{devLogin:true,prototypeHeaders:true},production:false}},
    async devLogin(payload){const a=window.PRO4X4_AUTH.setLocalRole(payload?.role||'customer',payload?.displayName);return {schemaVersion:'0.12.0',authenticated:true,source:'browser-local',actor:a,production:false}},
    async logout(){window.PRO4X4_AUTH.setLocalRole('customer','Local Customer');return {schemaVersion:'0.12.0',loggedOut:true}},
    async listQuotes(){return window.PRO4X4_SALES_STORE.list()},
    async getQuote(reference){return window.PRO4X4_SALES_STORE.get(reference)},
    async createBuild(payload){return window.PRO4X4_SALES_STORE.upsert(payload,{action:'quote.submitted'})},
    async recordRenderTelemetry(){return {accepted:true,mode:'browser-local'}},
    async listRenderTelemetry(){return []},
    async resolveRenderStack(payload={}){const manifest=window.Y62_RENDER_MANIFEST,view=manifest?.views?.[payload.viewId],layers=(payload.requirements||[]).map(r=>{const skuMatches=view?.layers?.filter(x=>x.id===r.layerId&&(x.exactSku||null)===(r.exactSku||null))||[],m=skuMatches.find(x=>Object.entries(r.state||{}).every(([k,v])=>x.renderState?.[k]===v)),blocked=m?.status==='blocked-fitment',reason=!m&&skuMatches.length&&Object.keys(r.state||{}).length?'render-state-not-registered':blocked?'fitment-blocked':'hosted-production-proof-required';return {layerId:r.layerId,exactSku:r.exactSku??null,stateKey:r.stateKey||null,requestedState:r.state||{},state:blocked?'blocked':'missing',reason,registryStatus:m?.status||null,assetId:null,binaryUrl:null,checksumSha256:null}});const counts={available:0,missing:layers.filter(x=>x.state==='missing').length,blocked:layers.filter(x=>x.state==='blocked').length};return {schemaVersion:'0.22.0',vehicleId:payload.vehicleId||null,viewId:payload.viewId||null,fallbackPolicy:'none',exactMatchRequired:true,productionReady:false,counts,layers,source:'browser-local-unverified'}},
    async updateQuote(reference,payload){if(reference!==payload?.reference)throw new Error('Reference mismatch');return window.PRO4X4_SALES_STORE.upsert(payload,{action:'quote.updated'})},
    async finaliseQuote(reference){const x=window.PRO4X4_SALES_STORE.get(reference);if(!x)throw Object.assign(new Error('Quote not found'),{status:404});if(!x.pricing?.isComplete||!x.fitmentReview?.allApproved)throw Object.assign(new Error('Formal quote blocked by unresolved fitment or pricing requirements'),{status:422,code:'quote_gate_blocked'});const settings=window.PRO4X4_SALES_STORE.getSettings(),issued=new Date(),valid=new Date(issued.getTime()+(settings.quoteValidityDays||14)*86400000);const out={...x,workflow:{...(x.workflow||{}),status:'quoted',lastUpdatedAt:issued.toISOString()},quoteFinalisation:{status:'finalised',quoteNumber:x.quoteFinalisation?.quoteNumber||`Q-${reference.replace(/^P4X4-/,'')}`,issuedAt:issued.toISOString(),validUntil:valid.toISOString(),customerTotal:x.pricing?.knownSubtotal||0,labourRateUsed:settings.labourRate??null}};return window.PRO4X4_SALES_STORE.upsert(out,{action:'quote.finalised'})},
    async getStaffSettings(){return window.PRO4X4_SALES_STORE.getSettings()},
    async setStaffSettings(payload){return window.PRO4X4_SALES_STORE.setSettings(payload)},
    async getCatalogue(vehicleId){const c=window.PRO4X4_CATALOGUE_STORE.getPublished()||window.PRO4X4_CATALOGUE_STORE.base();if(vehicleId&&c.vehicleId!==vehicleId)throw Object.assign(new Error('Catalogue not found'),{status:404});return c},
    async publishCatalogue(vehicleId,snapshot){if(vehicleId&&snapshot?.vehicleId&&vehicleId!==snapshot.vehicleId)throw new Error('Vehicle mismatch');return window.PRO4X4_CATALOGUE_STORE.publish(snapshot,window.PRO4X4_AUTH?.current()?.displayName||'PRO4X4 staff')},
    async getCatalogueDraft(){return window.PRO4X4_CATALOGUE_STORE.getDraft()},
    async saveCatalogueDraft(vehicleId,snapshot){if(vehicleId&&snapshot?.vehicleId&&vehicleId!==snapshot.vehicleId)throw new Error('Vehicle mismatch');return window.PRO4X4_CATALOGUE_STORE.saveDraft(snapshot)},
    async discardCatalogueDraft(){return window.PRO4X4_CATALOGUE_STORE.discardDraft()},
    async listRenderAssets(){return window.PRO4X4_ASSET_REGISTRY?.load?.()||[]},
    async syncVisualGovernance(vehicleId='nissan-y62-warrior-2025'){const records=window.PRO4X4_ASSET_REGISTRY?.load?.()||[],summary=window.PRO4X4_ASSET_REGISTRY?.summary?.(records)||{};return {schemaVersion:'0.26.2',vehicleId,createdCount:0,preservedCount:records.length,backfilledCount:0,created:[],preserved:records.map(x=>x.assetId),backfilled:[],summary}},
    async getRenderReadiness(vehicleId){return localReadiness(vehicleId)},
    async syncRenderReadinessSlots(vehicleId){return localSyncReadiness(vehicleId)},
    async upsertRenderAsset(record){return window.PRO4X4_ASSET_REGISTRY.upsert(record)},
    async uploadRenderAssetBinary(){throw Object.assign(new Error('Binary vault requires the hosted HTTP runtime'),{code:'vault_unavailable'})},
    async listRenderAssetVersions(){return []},async stageRenderAssetVersion(){throw Object.assign(new Error('Versioned binary vault requires the hosted HTTP runtime'),{code:'vault_unavailable'})},async updateRenderAssetVersion(){throw Object.assign(new Error('Version lineage requires the hosted HTTP runtime'),{code:'vault_unavailable'})},async promoteRenderAssetVersion(){throw Object.assign(new Error('Version lineage requires the hosted HTTP runtime'),{code:'vault_unavailable'})},async rejectRenderAssetVersion(){throw Object.assign(new Error('Version lineage requires the hosted HTTP runtime'),{code:'vault_unavailable'})},async getRenderAssetVersionDelivery(){throw Object.assign(new Error('Historical binary delivery requires the hosted HTTP runtime'),{code:'vault_unavailable'})},
    async listAudit(params){return window.PRO4X4_AUDIT_STORE.list(params||{})},
    async listProjects(){return window.PRO4X4_PROJECT_STORE.listProjects()},
    async getProject(id){const p=window.PRO4X4_PROJECT_STORE.getProject(id);if(!p)throw Object.assign(new Error('Project not found'),{status:404});return p},
    async saveProjectRevision(id,snapshot,opts={}){return window.PRO4X4_PROJECT_STORE.saveRevision(snapshot,{projectId:id,source:opts.source||'customer-builder',expectedVersion:opts.expectedVersion,title:opts.title})},
    async restoreProjectRevision(id,revisionId,opts={}){const snap=window.PRO4X4_PROJECT_STORE.restoreRevision(id,revisionId,{expectedVersion:opts.expectedVersion});if(!snap)throw Object.assign(new Error('Project/revision not found'),{status:404});return {project:window.PRO4X4_PROJECT_STORE.getProject(id),snapshot:snap}},
    async createProjectShare(id,payload={}){return window.PRO4X4_PROJECT_STORE.createShare(id,payload.role||'customer-view',payload.revisionId||null,payload.expiresDays??30)},
    async resolveProjectShare(token){const r=await window.PRO4X4_PROJECT_STORE.resolveShare(token);if(!r)throw Object.assign(new Error('Share not found, expired or revoked'),{status:404});return r},
    async revokeProjectShare(id,tokenHash){const ok=await window.PRO4X4_PROJECT_STORE.revokeShare(tokenHash);if(!ok)throw Object.assign(new Error('Share not found'),{status:404});return true},
    async getAssetVaultStatus(){return {healthy:true,mode:'browser-local',referencedObjects:0,vaultFiles:0,missing:[],orphaned:[],corrupt:[],totalBytes:0}},
    async gcAssetVault(){return {dryRun:true,orphanCount:0,orphans:[],removed:[]}},
    async exportBackup(){const keys=P.local.keys();return {schemaVersion:'0.12.0',exportedAt:new Date().toISOString(),mode:'localStorage',entries:Object.fromEntries(keys.map(k=>[k,P.local.get(k,null)]))}},
    async restoreBackup(bundle){if(!bundle?.entries)throw new Error('Local backup entries missing');Object.entries(bundle.entries).forEach(([k,v])=>P.local.set(k,v));return {schemaVersion:'0.12.0',restored:true,entryCount:Object.keys(bundle.entries).length}}
  };
  const mock=()=>{const http=P.httpMock();return wrapHttp(http,'http-mock')};
  const live=()=>wrapHttp(new P.HttpAdapter('/api/v1'),'http-server');
  function wrapHttp(http,mode){return {
    mode,
    health:()=>http.health(),getSession:()=>http.getSession(),devLogin:p=>http.devLogin(p),logout:()=>http.logout(),listQuotes:()=>http.listQuotes(),getQuote:r=>http.getQuote(r),createBuild:p=>http.createBuild(p),resolveRenderStack:p=>http.resolveRenderStack(p),recordRenderTelemetry:p=>http.recordRenderTelemetry(p),listRenderTelemetry:p=>http.listRenderTelemetry(p),updateQuote:(r,p)=>http.updateQuote(r,p),finaliseQuote:(r,p)=>http.finaliseQuote(r,p),
    getStaffSettings:()=>http.getStaffSettings(),setStaffSettings:p=>http.setStaffSettings(p),
    getCatalogue:v=>http.getCatalogue(v),publishCatalogue:(v,p)=>http.publishCatalogue(v,p),getCatalogueDraft:v=>http.getCatalogueDraft(v),saveCatalogueDraft:(v,p)=>http.saveCatalogueDraft(v,p),discardCatalogueDraft:v=>http.discardCatalogueDraft(v),
    listRenderAssets:v=>http.listRenderAssets(v),syncVisualGovernance:v=>http.syncVisualGovernance(v),getRenderReadiness:(v,h)=>http.getRenderReadiness(v,h),syncRenderReadinessSlots:v=>http.syncRenderReadinessSlots(v),upsertRenderAsset:r=>http.upsertRenderAsset(r),uploadRenderAssetBinary:(id,file)=>http.uploadRenderAssetBinary(id,file),listRenderAssetVersions:id=>http.listRenderAssetVersions(id),stageRenderAssetVersion:(id,file)=>http.stageRenderAssetVersion(id,file),updateRenderAssetVersion:(id,vid,p)=>http.updateRenderAssetVersion(id,vid,p),promoteRenderAssetVersion:(id,vid)=>http.promoteRenderAssetVersion(id,vid),rejectRenderAssetVersion:(id,vid,n)=>http.rejectRenderAssetVersion(id,vid,n),getRenderAssetVersionDelivery:(id,vid)=>http.getRenderAssetVersionDelivery(id,vid),
        listAudit:p=>http.listAudit(p),
    listProjects:()=>http.listProjects(),getProject:id=>http.getProject(id),saveProjectRevision:(id,s,o)=>http.saveRevision(id,s,o||{}),restoreProjectRevision:(id,r,o)=>http.restoreRevision(id,r,o||{}),createProjectShare:(id,p)=>http.createShare(id,p||{}),resolveProjectShare:t=>http.resolveShare(t),revokeProjectShare:(id,h)=>http.revokeProjectShare(id,h),
    getAssetVaultStatus:()=>http.getAssetVaultStatus(),gcAssetVault:e=>http.gcAssetVault(e),exportBackup:()=>http.exportBackup(),restoreBackup:b=>http.restoreBackup(b),importSeed:b=>http.importSeed(b)
  }}
  function active(){const q=new URLSearchParams(location.search).get('backend');if(q==='local')return local;if(q==='mock')return mock();if(q==='http')return live();return /^https?:$/.test(location.protocol)?live():local}
  window.PRO4X4_BACKEND={schemaVersion:'0.12.0',local,mock,live,active};
})();
