(function(){
  const P=window.PRO4X4_PERSISTENCE.local;
  const INDEX='projects:index-v1',PROJECT_PREFIX='projects:item:',SHARE_PREFIX='shares:hash:';
  const clone=v=>JSON.parse(JSON.stringify(v)); const now=()=>new Date().toISOString();
  const rand=(bytes=24)=>{const a=new Uint8Array(bytes);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')};
  const projectId=()=>`P4X4-PROJ-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${rand(6).slice(0,8).toUpperCase()}`;
  const checksum=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')};
  async function sha256(s){const bytes=new TextEncoder().encode(s);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  function readIndex(){return P.get(INDEX,[])} function writeIndex(items){P.set(INDEX,items);return items} function key(id){return PROJECT_PREFIX+id}
  function getProject(id){return P.get(key(id),null)}
  function listProjects(){return readIndex().map(id=>getProject(id)).filter(Boolean).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}
  function makeSummary(payload){return {reference:payload.reference,leadName:payload.lead?.name||'',vehicleId:payload.vehicle?.id||'',vehicleLabel:[payload.vehicle?.yearRange,payload.vehicle?.make,payload.vehicle?.model,payload.vehicle?.trim].filter(Boolean).join(' '),knownSubtotal:payload.pricing?.knownSubtotal||0,itemCount:payload.selections?.length||0,workflowStatus:payload.workflow?.status||'new',paint:payload.vehicle?.paint||'',catalogueRevision:payload.catalogue?.revision||''}}
  function saveRevision(payload,opts={}){
    const t=now();let id=opts.projectId||payload.project?.id||null;let project=id?getProject(id):null;const vehicleLabel=[payload.vehicle?.yearRange,payload.vehicle?.make,payload.vehicle?.model,payload.vehicle?.trim].filter(Boolean).join(' ')||'4WD Build';const defaultTitle=payload.lead?.name?`${payload.lead.name} · ${vehicleLabel}`:`${vehicleLabel} Build`;
    if(!project){id=projectId();project={schemaVersion:'0.12.0',id,title:opts.title||defaultTitle,vehicleId:payload.vehicle?.id||null,ownerId:opts.ownerId||window.PRO4X4_AUTH?.current()?.actorId||'local-customer',createdAt:t,updatedAt:t,version:0,currentRevisionId:null,revisions:[],shares:[],archived:false};const idx=readIndex();if(!idx.includes(id))writeIndex([id,...idx]);}
    if(opts.expectedVersion!=null&&Number(opts.expectedVersion)!==Number(project.version||0)){const e=new Error(`Project changed from version ${opts.expectedVersion} to ${project.version}. Reload before saving.`);e.code='VERSION_CONFLICT';e.currentVersion=project.version;throw e}
    const next=(project.revisions?.length||0)+1,revisionId=`R${String(next).padStart(4,'0')}`,snapshot=clone(payload),actor=window.PRO4X4_AUTH?.actorSnapshot?.()||{actorId:'local-unknown',role:'customer'};
    snapshot.schemaVersion='0.12.0';snapshot.project={id,revisionId,revisionNumber:next,savedAt:t,source:opts.source||'customer-builder',projectVersion:Number(project.version||0)+1};snapshot.actor=actor;snapshot.contract={...(snapshot.contract||{}),version:'0.12.0'};
    const serialized=JSON.stringify(snapshot),revision={id:revisionId,number:next,createdAt:t,source:opts.source||'customer-builder',actor,checksum:checksum(serialized),summary:makeSummary(snapshot),snapshot};
    project.schemaVersion='0.12.0';project.title=opts.title||project.title;project.updatedAt=t;project.currentRevisionId=revisionId;project.version=Number(project.version||0)+1;project.revisions=[...(project.revisions||[]),revision];project.vehicleId=snapshot.vehicle?.id||project.vehicleId;P.set(key(id),project);window.PRO4X4_AUDIT_STORE?.append(project.version===1?'project.created':'project.revision.saved','project',id,{revisionId,projectVersion:project.version,source:opts.source||'customer-builder',reference:snapshot.reference||null});return {project:clone(project),revision:clone(revision),snapshot:clone(snapshot)};
  }
  function currentRevision(project){if(!project)return null;return project.revisions?.find(r=>r.id===project.currentRevisionId)||project.revisions?.at(-1)||null}
  function getRevision(projectId,revisionId){const p=getProject(projectId);if(!p)return null;return p.revisions?.find(r=>r.id===revisionId)||currentRevision(p)}
  function restoreRevision(projectId,revisionId,opts={}){const p=getProject(projectId),r=getRevision(projectId,revisionId);if(!p||!r)return null;if(opts.expectedVersion!=null&&Number(opts.expectedVersion)!==Number(p.version||0)){const e=new Error('Version conflict while restoring revision');e.code='VERSION_CONFLICT';throw e}p.currentRevisionId=r.id;p.updatedAt=now();p.version=Number(p.version||0)+1;P.set(key(projectId),p);window.PRO4X4_AUDIT_STORE?.append('project.revision.restored','project',projectId,{revisionId:r.id,projectVersion:p.version});return clone(r.snapshot)}
  async function createShare(projectId,role='customer-view',revisionId=null,expiresDays=30){const p=getProject(projectId);if(!p)throw new Error('Project not found');const r=getRevision(projectId,revisionId||p.currentRevisionId);if(!r)throw new Error('Revision not found');const token=rand(32),tokenHash=await sha256(token),createdAt=now(),expiresAt=expiresDays?new Date(Date.now()+expiresDays*86400000).toISOString():null;const stored={schemaVersion:'0.12.0',tokenHash,tokenHint:token.slice(-6),projectId,revisionId:r.id,role,createdAt,expiresAt,revokedAt:null,localPrototype:true};P.set(SHARE_PREFIX+tokenHash,stored);p.shares=[...(p.shares||[]),{tokenHash,tokenHint:stored.tokenHint,revisionId:r.id,role,createdAt,expiresAt,revokedAt:null}];p.updatedAt=createdAt;p.version=Number(p.version||0)+1;P.set(key(projectId),p);window.PRO4X4_AUDIT_STORE?.append('project.share.created','project',projectId,{revisionId:r.id,role,expiresAt,tokenHint:stored.tokenHint});return {...clone(stored),token};}
  async function resolveShare(token){const tokenHash=await sha256(token),s=P.get(SHARE_PREFIX+tokenHash,null);if(!s||s.revokedAt)return null;if(s.expiresAt&&Date.parse(s.expiresAt)<Date.now())return null;const p=getProject(s.projectId),r=p?.revisions?.find(x=>x.id===s.revisionId);return p&&r?{share:clone(s),project:clone(p),revision:clone(r)}:null}
  async function revokeShare(tokenOrHash){const tokenHash=/^[a-f0-9]{64}$/i.test(tokenOrHash)?tokenOrHash:await sha256(tokenOrHash),s=P.get(SHARE_PREFIX+tokenHash,null);if(!s)return false;s.revokedAt=now();P.set(SHARE_PREFIX+tokenHash,s);const p=getProject(s.projectId);if(p){p.shares=(p.shares||[]).map(x=>x.tokenHash===tokenHash?{...x,revokedAt:s.revokedAt}:x);p.updatedAt=s.revokedAt;p.version=Number(p.version||0)+1;P.set(key(p.id),p);window.PRO4X4_AUDIT_STORE?.append('project.share.revoked','project',p.id,{revisionId:s.revisionId,role:s.role,tokenHint:s.tokenHint})}return true}
  function exportProject(id){return getProject(id)}
  function deleteProject(id){const p=getProject(id);if(!p)return false;(p.shares||[]).forEach(s=>P.remove(SHARE_PREFIX+s.tokenHash));P.remove(key(id));writeIndex(readIndex().filter(x=>x!==id));window.PRO4X4_AUDIT_STORE?.append('project.deleted','project',id,{revisionCount:p.revisions?.length||0});return true}
  window.PRO4X4_PROJECT_STORE={schemaVersion:'0.12.0',listProjects,getProject,currentRevision,getRevision,saveRevision,restoreRevision,createShare,resolveShare,revokeShare,exportProject,deleteProject,sha256};
})();
