const $=s=>document.querySelector(s),manifest=window.Y62_RENDER_MANIFEST,contracts=window.Y62_RENDER_CONTRACTS,data=window.Y62_DATA,backend=window.PRO4X4_BACKEND.active();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function fillSelectors(){const p=$('#previewPaint'),w=$('#previewWheel');p.innerHTML='';for(const x of data.vehicle.paints||[]){const o=document.createElement('option');o.value=x.id;o.textContent=x.label+(x.visualReady===false?' · VISUAL PENDING':'');o.disabled=!x.validated;p.appendChild(o)}w.innerHTML='';for(const x of data.vehicle.wheelTyres||[]){const o=document.createElement('option');o.value=x.id;o.textContent=x.label;o.disabled=!x.validated;w.appendChild(o)}p.value='black-obsidian';w.value='factory-warrior'}
function layerState(x){if(x.id==='base')return {state:{paintId:$('#previewPaint').value},stateKey:`paint:${$('#previewPaint').value}`};if(x.id==='wheels')return {state:{wheelTyreId:$('#previewWheel').value},stateKey:`wheel:${$('#previewWheel').value}`};return {state:{},stateKey:null}}
function reqs(viewId){const sel=new Set((data.accessories||[]).filter(x=>x.selected).map(x=>x.layer));return manifest.views[viewId].layers.filter(x=>x.id==='base'||x.id==='wheels'||sel.has(x.id)||sel.has(x.id.replace(/-(wheel|jerry|camera)$/,''))).sort((a,b)=>a.priority-b.priority).map(x=>({layerId:x.id,exactSku:x.exactSku??null,...layerState(x)}))}
async function loadImage(img,x,policy,stats){const max=Math.max(1,Number(policy?.maxAttempts)||3),delays=policy?.retryDelaysMs||[0,350,900],timeoutMs=Number(policy?.timeoutMs)||8000;for(let attempt=1;attempt<=max;attempt++){const ok=await new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);img.onload=null;img.onerror=null;resolve(v)},timer=setTimeout(()=>finish(false),timeoutMs);img.onload=()=>finish(true);img.onerror=()=>finish(false);const sep=x.binaryUrl.includes('?')?'&':'?';img.src=x.binaryUrl+(attempt>1?`${sep}previewAttempt=${attempt}`:'')});if(ok){stats.delivered++;return {state:'loaded',attempt}}if(attempt<max){stats.retries++;await wait(Number(delays[attempt]??delays.at(-1)??350))}}img.remove();return {state:'failed',attempt:max}}
async function refresh(){
  const v=$('#previewView').value,c=contracts.contracts[v],requirements=reqs(v),stack=$('#previewStack'),empty=$('#previewEmpty'),diag=$('#previewDiagnostics');stack.innerHTML='';diag.innerHTML='';$('#previewContract').textContent=c?.contractId||'NO CONTRACT';$('#previewState').textContent=`${$('#previewPaint').value} / ${$('#previewWheel').value}`;$('#previewTelemetry').textContent='CHECKING';
  const r=await backend.resolveRenderStack({vehicleId:data.vehicle.id,viewId:v,requirements}),available=r.layers.filter(x=>x.state==='available'),stats={delivered:0,retries:0};$('#previewResolved').textContent=`${available.length}/${r.layers.length}`;$('#previewDelivered').textContent=`0/${available.length}`;$('#previewRetries').textContent='0';
  const base=r.layers.find(x=>x.layerId==='base');empty.classList.remove('hidden');empty.querySelector('b').textContent=base?.state==='available'?'LOADING APPROVED BASE':'NO APPROVED BASE';empty.querySelector('span').textContent=base?.state==='available'?'Verifying exact production delivery. No fallback will be shown.':`Exact state ${requirements.find(x=>x.layerId==='base')?.stateKey||''} is not production-ready.`;
  const loadResults=new Map();for(const x of available){const i=document.createElement('img');i.className='production-layer';i.alt=`${x.layerId} production layer`;stack.appendChild(i);const result=await loadImage(i,x,c?.loadPolicy,stats);loadResults.set(x.layerId,result);$('#previewDelivered').textContent=`${stats.delivered}/${available.length}`;$('#previewRetries').textContent=String(stats.retries);if(x.layerId==='base'&&result.state==='loaded')empty.classList.add('hidden')}
  $('#previewSummary').textContent=`${c?.contractId||'NO CONTRACT'} · ${r.counts.available} available · ${r.counts.missing} missing · ${r.counts.blocked} blocked · exact-state only · fallback NONE`;
  r.layers.forEach((x,i)=>{const load=loadResults.get(x.layerId),d=document.createElement('div');d.className=`diag-item ${x.state==='available'&&load?.state==='failed'?'error':x.state}`;d.textContent=`${String(i+1).padStart(2,'0')} · ${x.layerId} · ${x.state.toUpperCase()}${x.stateKey?' · '+x.stateKey:''}${x.exactSku?' · '+x.exactSku:''}${load?' · delivery '+load.state+' #'+load.attempt:''}${x.reason?' · '+x.reason:''}`;diag.appendChild(d)});
  try{const events=await backend.listRenderTelemetry({vehicleId:data.vehicle.id,viewId:v,limit:50}),fails=events.filter(x=>x.eventType==='asset-load-error').length,retries=events.filter(x=>x.eventType==='asset-load-retry').length;$('#previewTelemetry').textContent=`${events.length} EVT · ${retries} RETRY · ${fails} FAIL`}catch{$('#previewTelemetry').textContent='STAFF API N/A'}
}
fillSelectors();$('#refreshPreview').onclick=()=>refresh().catch(e=>$('#previewSummary').textContent=e.message);$('#previewView').onchange=()=>refresh();$('#previewPaint').onchange=()=>refresh();$('#previewWheel').onchange=()=>refresh();refresh().catch(e=>$('#previewSummary').textContent=e.message);
