
import * as THREE from "three";import {GLTFLoader} from "three/addons/loaders/GLTFLoader.js";import {OrbitControls} from "three/addons/controls/OrbitControls.js";
export async function startRuntime(getState) {

const host=document.querySelector('#stage'),st=document.querySelector('#status'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(28,1,.05,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);camera.position.set(4.7,2.6,6.8);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.9,0);controls.enablePan=false;controls.minDistance=4;controls.maxDistance=10;controls.update();scene.add(new THREE.HemisphereLight(0xffffff,0x182027,2.3));for(const [p,i] of [[[5,7,8],4],[[-5,4,4],2],[[0,6,-6],2.5]]){const l=new THREE.DirectionalLight(0xffffff,i);l.position.set(...p);scene.add(l)}const root=new THREE.Group();scene.add(root);const loader=new GLTFLoader();let base,factoryFront,factoryRear,pred,rally,lights,scout,powerboards,tubrack,rearbumper;
try{const [r,f,fr,p,h,l,s,pb,tr,rb]=await Promise.all([loader.loadAsync('ranger-static-front-rear.glb'),loader.loadAsync('factory-front.glb'),loader.loadAsync('factory-rear.glb'),loader.loadAsync('predator.glb'),loader.loadAsync('rally-hoop-v3.glb'),loader.loadAsync('butt-kicker-7-pair-v1.glb'),loader.loadAsync('scout.glb'),loader.loadAsync('powerboards.glb'),loader.loadAsync('tubrack.glb'),loader.loadAsync('rearbumper.glb')]);base=r.scene;root.add(base);factoryFront=f.scene;factoryRear=fr.scene;pred=p.scene;rally=h.scene;lights=l.scene;scout=s.scene;powerboards=pb.scene;tubrack=tr.scene;rearbumper=rb.scene;root.add(factoryFront,factoryRear,pred,rally,lights,scout,powerboards,tubrack,rearbumper);apply(getState());st.textContent='READY · FRONT + REAR REPLACEMENT STATES';document.getElementById('runtimeGate').textContent='RUNTIME CHECK · 10/10 3D ASSETS LOADED'}catch(e){console.error(e);st.textContent='3D ASSET LOAD ERROR'}
function apply(state){const nodes={base,factoryFront,factoryRear,predator:pred,rally,lights,scout,powerboards,tubrack,rearbumper};for(const [key,node] of Object.entries(nodes))if(node)node.visible=state.layers[key]?.visible===true;host.dataset.renderState=JSON.stringify(Object.fromEntries(Object.entries(nodes).map(([key,node])=>[key,!!node?.visible])));host.dataset.eligibility=state.baseState;}
window.addEventListener('rigchange',e=>apply(e.detail));window.addEventListener('resetview',()=>{camera.position.set(4.7,2.6,6.8);controls.target.set(0,.9,0);controls.update()});window.addEventListener('setview',e=>{camera.position.set(...(e.detail==='front'?[0,1.7,7.2]:[4.7,2.6,6.8]));controls.target.set(0,.9,0);controls.update()});function resize(){const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}new ResizeObserver(resize).observe(host);resize();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});

}
